from flask import Flask, jsonify, send_file, request
import os, json
app = Flask(__name__)
BASE_DATA = '/tmp/data' if os.path.exists('/tmp') else 'data'
os.makedirs(BASE_DATA, exist_ok=True)
USERS_FILE = os.path.join(BASE_DATA, 'users.json')
def load_users():
 try:
  if os.path.exists(USERS_FILE):
   with open(USERS_FILE,'r') as f: return json.load(f)
 except: pass
 return {}
def save_users(u):
 try:
  with open(USERS_FILE,'w') as f: json.dump(u,f)
 except: pass
def get_user_file(nid):
 safe=nid.replace("@","_at_").replace(".","_")
 return os.path.join(BASE_DATA, f"{safe}.json")

@app.route('/manifest.json')
def manifest():
 return jsonify({"name":"Mi Negocio 11.6","short_name":"Mi Negocio","start_url":"/","display":"standalone","icons":[{"src":"/logo.png","sizes":"512x512","type":"image/png"},{"src":"/api/logo.png","sizes":"512x512","type":"image/png"}]})
@app.route('/logo.png')
@app.route('/api/logo.png')
def logo_file():
 posibles = ['logo.png','api/logo.png',os.path.join(os.path.dirname(__file__), 'logo.png'),os.path.join(os.getcwd(), 'logo.png'),os.path.join(os.getcwd(), 'api', 'logo.png'),'/tmp/logo.png']
 for ruta in posibles:
  try:
   if os.path.exists(ruta):
    return send_file(ruta, mimetype='image/png')
  except: pass
 return "",204
@app.route('/api/register', methods=['POST'])
def api_register():
 d=request.json; email=d.get('email','').lower().strip(); pwd=d.get('password','')
 users=load_users()
 if email in users: return jsonify({"ok":False,"msg":"Ya existe"}),400
 users[email]={"password":pwd,"negocio_id":email,"rol":"owner"}; save_users(users)
 with open(get_user_file(email),'w') as f: json.dump({},f)
 return jsonify({"ok":True})
@app.route('/api/login', methods=['POST'])
def api_login():
 d=request.json; email=d.get('email','').lower().strip(); pwd=d.get('password','')
 users=load_users()
 if email not in users or users[email]['password']!=pwd: return jsonify({"ok":False,"msg":"Error"}),401
 return jsonify({"ok":True,"email":email,"negocio_id":users[email]['negocio_id'],"rol":users[email]['rol']})
@app.route('/api/invite', methods=['POST'])
def api_invite():
 d=request.json; owner=d.get('owner_email','').lower().strip(); owner_pwd=d.get('owner_password',''); colab=d.get('colab_email','').lower().strip(); colab_pwd=d.get('colab_password','') or '1234'
 users=load_users()
 if owner not in users or users[owner]['password']!=owner_pwd: return jsonify({"ok":False,"msg":"No autorizado"}),403
 users[colab]={"password":colab_pwd,"negocio_id":users[owner]['negocio_id'],"rol":"colab"}; save_users(users)
 return jsonify({"ok":True})
@app.route('/api/load', methods=['GET'])
def api_load():
 email=request.args.get('email','').lower().strip(); users=load_users()
 if email not in users: return jsonify({"ok":False}),404
 data=json.load(open(get_user_file(users[email]['negocio_id']))) if os.path.exists(get_user_file(users[email]['negocio_id'])) else {}
 return jsonify({"ok":True,"data":data})
@app.route('/api/save', methods=['POST'])
def api_save():
 d=request.json; email=d.get('email','').lower().strip(); data=d.get('data',{})
 users=load_users()
 if email not in users: return jsonify({"ok":False}),404
 with open(get_user_file(users[email]['negocio_id']),'w') as f: json.dump(data,f)
 return jsonify({"ok":True})
@app.route('/')
@app.route('/api')
@app.route('/api/')
def home():
 return '''<!DOCTYPE html><html><head><link rel="manifest" href="/manifest.json"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mi Negocio 11.6</title><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><style>input,select,textarea{color:#000!important;background:#fff!important}.logo-watermark{position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);width:650px;height:650px;pointer-events:none;z-index:0;opacity:0.18;object-fit:contain;}#appContent{position:relative;z-index:1;}#splashInicio{position:fixed;inset:0;background:white;z-index:9999;display:flex;flex-direction:column;align-items:center;justify-content:center}#splashInicio img{width:85vw;max-width:380px;height:auto;animation:pop 0.8s ease}@keyframes pop{0%{transform:scale(0.5);opacity:0}100%{transform:scale(1);opacity:1}}</style></head><body class="bg-[#FFF8F0] min-h-screen"><div id="splashInicio"><img src="/logo.png" onerror="this.src='/api/logo.png'"><p style="margin-top:20px;font-weight:900;font-size:22px">Mi Negocio 11.6</p><p style="font-size:12px;color:#888">Cargando...</p></div><script>setTimeout(()=>{let s=document.getElementById('splashInicio'); if(s) s.style.display='none'},1800)</script><div class="max-w-md mx-auto pb-[140px] relative"><img id="logoBg" class="logo-watermark hidden"><div id="appContent">
<div id="loginScreen" class="fixed inset-0 bg-[#FFF8F0] z-[100] flex flex-col items-center justify-center p-6"><h1 class="font-black text-[24px]">Mi Negocio 11.6</h1><p class="text-[11px] text-gray-500">11.6 - stock auto + barcode + respaldo + corte turno</p><div class="bg-white w-full rounded-[28px] p-5 shadow-xl border-2 border-black mt-6"><input id="loginEmail" type="email" placeholder="Correo" class="w-full border-2 border-black p-4 rounded-2xl font-bold text-[14px]"><input id="loginPass" type="password" placeholder="Contraseña" class="w-full border-2 border-black p-4 rounded-2xl font-bold text-[14px] mt-3"><button onclick="hacerLogin()" class="w-full mt-4 bg-black text-white py-4 rounded-2xl font-black">ENTRAR</button><button onclick="hacerRegistro()" class="w-full mt-2 bg-white border-2 border-black py-3 rounded-2xl font-bold text-[13px]">REGISTRARME</button><p id="loginMsg" class="hidden mt-3 text-[11px] font-bold text-center p-2 rounded-xl"></p></div></div>
<div class="bg-white p-3 flex justify-between items-center sticky top-0 z-20 shadow-sm"><div class="flex items-center gap-3"><img id="logoHeader" class="w-20 h-20 rounded-full object-cover border-[4px] border-black hidden shadow-xl" onerror="this.src='/api/logo.png'"><div><h1 class="font-black text-[16px]">Mi Negocio 11.6</h1><p id="userLabel" class="text-[10px] text-gray-500"></p><p id="horaActual" class="text-[10px] font-black text-green-600"></p></div></div><div class="flex gap-2"><button onclick="showTab('config')" class="text-[10px] bg-black text-white px-3 py-2 rounded-full">Config</button><button onclick="cerrarSesion()" class="text-[10px] bg-red-100 text-red-600 px-2 py-1 rounded-full">Salir</button></div></div>

<div id="tab-vender" class="p-3 hidden">
<div class="bg-black text-white rounded-[20px] p-3 mb-3 flex gap-2 items-center"><i class="fa-solid fa-barcode text-yellow-400"></i><input id="scanBarcode" placeholder="Escanea código / Enter" class="flex-1 bg-white text-black border-2 border-yellow-400 p-2 rounded-xl text-[13px] font-black" onkeydown="if(event.key==='Enter'){buscarPorBarcode(this.value); this.value='';}"><button onclick="iniciarScanner()" class="bg-yellow-400 text-black px-3 py-2 rounded-xl font-black text-[11px]">📷</button></div>
<div id="reader" class="hidden w-full h-64 rounded-xl overflow-hidden border-2 border-black mb-3"></div>
<div class="bg-white rounded-[20px] p-3 shadow-sm mb-3"><div class="flex justify-between items-center"><h3 class="font-black text-[13px]">Categorías</h3><button onclick="document.getElementById('boxNuevaCat').classList.toggle('hidden')" class="text-[10px] bg-black text-white px-3 py-1 rounded-full">+ Nueva</button></div><div id="filtrosCats" class="flex gap-2 mt-3 overflow-x-auto pb-2"></div><div id="boxNuevaCat" class="hidden mt-3 bg-amber-50 border-2 p-3 rounded-xl"><div id="listaCatsEdit" class="space-y-2 mb-3"></div><div class="grid grid-cols-5 gap-2"><input id="nuevaCatNombre" placeholder="Ej: Alitas" class="col-span-4 border-2 border-black p-2 rounded-xl text-[12px] font-bold"><button onclick="addCategoriaVenta()" class="bg-black text-white rounded-xl font-black">+</button></div></div></div>
<div id="alertaStock" class="hidden bg-red-100 border-2 border-red-300 rounded-xl p-2 mb-3 text-[11px] font-bold text-red-700"></div>
<div id="listaVenta" class="grid grid-cols-2 gap-3"></div>
<div class="mt-6 bg-white rounded-[28px] p-4 shadow-xl border-2 border-black"><div class="bg-yellow-50 border-2 border-yellow-300 rounded-xl p-2 mb-3"><p class="text-[10px] font-black">👤 Cliente</p><select id="selCliente" class="w-full border-2 border-black p-3 rounded-xl text-[12px] font-bold mt-2"></select><div class="flex gap-2 mt-2"><input id="quickClienteNombre" placeholder="Nombre" class="flex-1 border-2 border-black p-2 rounded-xl text-[11px] font-bold"><input id="quickClienteTel" placeholder="WhatsApp" class="flex-1 border-2 border-black p-2 rounded-xl text-[11px] font-bold"><button onclick="addClienteRapido()" class="bg-black text-white px-3 rounded-xl font-black text-[12px]">+</button></div></div><div id="ticket" class="space-y-2">Vacío</div><div class="mt-3 bg-gray-50 p-2 rounded-xl flex gap-2 items-center"><span class="text-[11px] font-black">Descuento %</span><input id="descPorc" type="number" value="0" class="w-16 border-2 border-black p-1 rounded-xl text-center font-black" oninput="renderCarrito()"><span class="text-[10px]">Motivo</span><input id="descMotivo" placeholder="Promo" class="flex-1 border-2 border-black p-1 rounded-xl text-[10px]"></div><div class="flex justify-between font-black text-[20px] mt-3 border-t-2 pt-3">Total $ <span id="c-total">0</span></div><button onclick="abrirCobro()" class="w-full mt-3 bg-black text-white py-4 rounded-2xl font-black">COBRAR</button></div></div>

<div id="tab-config" class="p-3 hidden"><div class="bg-white rounded-[28px] p-5 shadow-sm"><h2 class="font-black">⚙️ Configuración 11.6</h2>
<div class="mt-4 bg-green-50 border-2 border-green-300 rounded-[20px] p-4"><p class="font-black text-[13px]">💾 Respaldo 1 clic - NUEVO</p><div class="grid grid-cols-2 gap-2 mt-3"><button onclick="exportarRespaldo()" class="bg-black text-white py-3 rounded-xl font-black text-[12px]">⬇️ DESCARGAR</button><label class="bg-yellow-400 border-2 border-black py-3 rounded-xl font-black text-[12px] text-center cursor-pointer">⬆️ RESTAURAR<input type="file" id="inputRestore" accept=".json" class="hidden" onchange="importarRespaldo(this)"></label></div></div>
<div class="mt-4 bg-blue-50 border-2 border-blue-200 rounded-[20px] p-4"><p class="font-black text-[13px]">📸 Logo</p><input type="file" id="logoInput" accept="image/*" onchange="previewLogo(this)" class="w-full mt-2 text-[12px]"><div id="logoPreviewBox" class="mt-3 hidden flex gap-3 items-center"><img id="logoPreview" class="w-28 h-28 object-contain rounded-xl border-2 border-black bg-white"><button onclick="quitarLogo()" class="text-[10px] bg-red-100 text-red-600 px-3 py-1 rounded-full font-bold">X</button></div><div class="mt-3 grid grid-cols-2 gap-2"><label class="text-[11px] font-bold flex items-center gap-1"><input type="checkbox" id="empMostrarLogo" checked> Logo en ticket</label><label class="text-[11px] font-bold flex items-center gap-1"><input type="checkbox" id="empMostrarFondo" checked> Fondo grande app</label></div><div class="mt-3"><p class="text-[11px] font-bold">Opacidad fondo</p><input type="range" id="empOpacidad" min="2" max="30" value="18" class="w-full" oninput="document.getElementById('opacidadVal').innerText=this.value+'%'; actualizarFondo();"><span id="opacidadVal" class="text-[10px]">18%</span></div></div>
<div class="mt-4 bg-gray-50 border-2 rounded-[20px] p-4"><p class="font-black text-[12px]">🏪 Datos del negocio</p><input id="empNombre" placeholder="Mi s receta" class="w-full border-2 border-black p-3 rounded-xl mt-3 font-bold"><input id="empDireccion" placeholder="Dirección" class="w-full border-2 border-black p-3 rounded-xl mt-2 text-[13px]"><div class="grid grid-cols-2 gap-2 mt-2"><input id="empCP" placeholder="C.P." class="border-2 border-black p-3 rounded-xl text-[13px]"><input id="empTel" placeholder="Tel" class="border-2 border-black p-3 rounded-xl text-[13px]"></div><input id="empRFC" placeholder="RFC" class="w-full border-2 border-black p-3 rounded-xl mt-2 text-[13px]"><textarea id="empMensaje" placeholder="¡Gracias!" class="w-full border-2 border-black p-3 rounded-xl mt-2 text-[12px]" rows="2"></textarea></div>
<div class="mt-4 bg-purple-50 border-2 border-purple-200 rounded-2xl p-3"><p class="font-black text-[12px]">👥 Colaboradores</p><div class="grid grid-cols-5 gap-2 mt-2"><input id="colabEmail" type="email" placeholder="colab@gmail.com" class="col-span-3 border-2 border-black p-2 rounded-xl text-[12px]"><input id="colabPass" placeholder="Pass" class="col-span-1 border-2 border-black p-2 rounded-xl text-[11px]"><button onclick="invitarColab()" class="bg-purple-600 text-white rounded-xl font-black">+</button></div></div>
<button onclick="guardarEmpresa()" class="w-full mt-4 bg-black text-white py-4 rounded-2xl font-black">GUARDAR</button><div id="ticketVista" class="mt-6 border-2 border-dashed border-black p-3 rounded-xl bg-yellow-50"><p class="text-[11px] font-black text-center mb-2">VISTA PREVIA</p><div id="ticketContenido" class="bg-white p-4 rounded-xl text-[12px] font-mono shadow-sm border"></div></div>
</div></div>
<div id="tab-clientes" class="p-3 hidden"><div class="bg-[#2D3748] rounded-[28px] p-4 text-white"><div class="flex justify-between items-center"><h2 class="font-black">👥 Clientes</h2><span class="text-[10px] bg-red-500 px-2 py-1 rounded-full font-black" id="totalDeudaGlobal">$0 por cobrar</span></div><div class="grid grid-cols-5 gap-2 mt-3"><input id="cliNombre" placeholder="Nombre" class="col-span-2 border-2 border-black p-2 rounded-xl text-[12px] text-black"><input id="cliTel" placeholder="WhatsApp" class="col-span-2 border-2 border-black p-2 rounded-xl text-[12px] text-black"><button onclick="addCliente()" class="bg-[#25D366] text-white rounded-xl font-black">+</button></div></div><div class="mt-3 bg-white rounded-[20px] p-4"><div id="listaClientes" class="space-y-3"></div></div></div>
<div id="tab-proveedores" class="p-3 hidden"><div class="bg-[#0F172A] rounded-[28px] p-4 text-white"><h2 class="font-black">🏭 Proveedores</h2><div class="grid grid-cols-7 gap-1 mt-3"><input id="provNombre" placeholder="Nombre" class="col-span-3 border-2 border-black p-2 rounded-xl text-[12px] text-black"><input id="provTel" placeholder="Tel" class="col-span-2 border-2 border-black p-2 rounded-xl text-[12px] text-black"><input id="provQue" placeholder="Qué" class="col-span-1 border-2 border-black p-2 rounded-xl text-[10px] text-black"><button onclick="addProveedor()" class="col-span-1 bg-yellow-400 text-black rounded-xl font-black">+</button></div></div><div class="mt-3 bg-white rounded-[20px] p-4"><div id="listaProveedores" class="space-y-3"></div></div></div>
<div id="tab-inventario" class="p-3 hidden"><div class="bg-[#2D3748] rounded-[28px] p-4 text-white mb-3"><h2 class="font-black">📦 Inventario + descuento auto</h2></div><div class="bg-white rounded-[20px] p-4"><div class="grid grid-cols-7 gap-1"><input id="inv-nombre" placeholder="Papas" class="col-span-2 border-2 border-black p-2 rounded-xl font-bold text-[12px]"><input id="inv-precio" type="number" placeholder="$30" class="col-span-1 border-2 border-black p-2 rounded-xl font-black text-[12px]"><input id="inv-stock" type="text" placeholder="500 g" class="col-span-2 border-2 border-black p-2 rounded-xl font-black text-[12px] bg-yellow-50"><select id="inv-unidad" class="col-span-1 border-2 border-black p-2 rounded-xl text-[10px] font-bold"><option>kg</option><option>g</option><option>L</option><option>ml</option><option>pza</option></select><button onclick="addInventario()" class="col-span-1 bg-black text-white rounded-xl font-black">+</button></div><div id="listaInvMaster" class="mt-4"></div></div></div>
<div id="tab-finanzas" class="p-3 hidden"><div class="bg-[#2D3748] rounded-[24px] p-4 text-white"><div class="flex justify-between items-center"><h2 class="font-black">📅 Finanzas - corte turno</h2><div class="flex gap-2"><button onclick="openGasto()" class="bg-[#4FD1C5] text-black px-3 h-10 rounded-xl font-black text-[11px]">+ MOV</button><button onclick="abrirCierre()" class="bg-yellow-400 text-black px-3 h-10 rounded-xl font-black text-[11px]">📦 CIERRE</button></div></div><div class="mt-3 grid grid-cols-3 gap-2"><div class="bg-white/10 rounded-xl p-2 text-center"><p class="text-[9px]">BALANCE</p><p class="font-black text-[14px]" id="fin-balance">$0</p></div><div class="bg-green-500/20 rounded-xl p-2 text-center"><p class="text-[9px]">ENTRADAS</p><p class="font-black text-[14px]" id="fin-entradas">$0</p></div><div class="bg-red-500/20 rounded-xl p-2 text-center"><p class="text-[9px]">SALIDAS</p><p class="font-black text-[14px]" id="fin-salidas">$0</p></div></div><div class="mt-3 grid grid-cols-4 gap-2"><div class="bg-white/10 rounded-xl p-2 text-center"><p class="text-[8px]">💵 EFEC</p><p class="font-black text-[12px]" id="fin-efectivo">$0</p></div><div class="bg-white/10 rounded-xl p-2 text-center"><p class="text-[8px]">💳 TARJ</p><p class="font-black text-[12px]" id="fin-tarjeta">$0</p></div><div class="bg-white/10 rounded-xl p-2 text-center"><p class="text-[8px]">🏦 TRANS</p><p class="font-black text-[12px]" id="fin-transf">$0</p></div><div class="bg-red-500/20 rounded-xl p-2 text-center"><p class="text-[8px]">📒 FIADO</p><p class="font-black text-[12px]" id="fin-fiado">$0</p></div></div></div><div class="mt-3 bg-white rounded-[24px] p-4 shadow-sm"><div class="flex justify-between items-center"><button onclick="moverCal(-1)" class="w-9 h-9 bg-gray-100 rounded-full font-black"><</button><h3 id="calTitulo" class="font-black text-[14px]"></h3><button onclick="moverCal(1)" class="w-9 h-9 bg-gray-100 rounded-full font-black">></button></div><div id="calGrid" class="mt-4"></div></div><div id="desgloseDia" class="mt-3 bg-white rounded-[24px] p-4 shadow-sm border-2 border-black"><h3 class="font-black text-[13px]">Desglose <span id="fechaSelLabel"></span> - <span id="labelTurno" class="text-blue-600"></span></h3><div id="flu-lista" class="mt-4 space-y-2"></div></div></div>
<div id="modalCobro" class="hidden fixed inset-0 bg-black/70 z-50 flex items-end justify-center"><div class="bg-white w-full max-w-md rounded-t-[28px] p-5 max-h-[90vh] overflow-y-auto"><h2 class="font-black text-[14px]">Cobrar $<span id="cobroTotal">0</span></h2><div class="mt-3"><p class="text-[11px] font-black">💳 Método</p><div class="grid grid-cols-3 gap-2 mt-2"><button onclick="setMetodoPago('Efectivo')" id="mp-efectivo" class="py-3 rounded-xl border-2 font-black text-[12px] bg-black text-white border-black">💵 Efectivo</button><button onclick="setMetodoPago('Tarjeta')" id="mp-tarjeta" class="py-3 rounded-xl border-2 font-bold text-[12px] bg-white border-black">💳 Tarjeta</button><button onclick="setMetodoPago('Transferencia')" id="mp-transferencia" class="py-3 rounded-xl border-2 font-bold text-[12px] bg-white border-black">🏦 Transfer.</button></div><div class="grid grid-cols-2 gap-2 mt-2"><button onclick="setMetodoPago('Fiado')" id="mp-fiado" class="py-3 rounded-xl border-2 font-bold text-[12px] bg-orange-100 border-orange-400">📒 Fiado</button><button onclick="setMetodoPago('Apartado')" id="mp-apartado" class="py-3 rounded-xl border-2 font-bold text-[12px] bg-purple-100 border-purple-400">📦 Apartado</button></div><input type="hidden" id="metodoPago" value="Efectivo"></div><div id="boxPagoEfectivo"><input id="pagoRecibido" type="number" placeholder="$ Recibido" class="w-full border-2 border-black p-3 rounded-xl mt-3 font-black text-[18px]" oninput="calcCambio()"><p class="mt-2 font-black text-[13px]">Cambio: $<span id="cambio">0.00</span></p></div><div class="grid grid-cols-2 gap-2 mt-4"><button onclick="confirmarCobro('print')" class="bg-black text-white py-4 rounded-2xl font-black text-[13px]">🖨️ IMPRIMIR</button><button onclick="confirmarCobro('whatsapp')" class="bg-[#25D366] text-white py-4 rounded-2xl font-black text-[13px]">📲 WHATSAPP</button></div><button onclick="confirmarCobro('solo')" class="w-full mt-2 bg-gray-100 py-3 rounded-xl font-bold text-[13px]">Solo cobrar</button><button onclick="cerrarCobro()" class="w-full mt-2 bg-white border-2 border-black py-2 rounded-xl">Cancelar</button></div></div>
<div id="modalCierre" class="hidden fixed inset-0 bg-black/70 z-50 flex items-end justify-center"><div class="bg-white w-full max-w-md rounded-t-[28px] p-5 max-h-[85vh] overflow-y-auto"><h2 class="font-black text-[16px]">📦 Cierre <span id="cierreFechaLabel"></span> - <span id="cierreUserLabel" class="text-blue-600"></span></h2><div class="mt-4 space-y-3"><div class="bg-black text-white p-4 rounded-2xl"><div class="flex justify-between"><span>Ventas hoy (tu turno)</span><b id="cierreTotal">$0</b></div><div class="flex justify-between mt-2 text-green-300"><span>💵 Efectivo</span><b id="cierreEfectivo">$0</b></div><div class="flex justify-between text-blue-300"><span>💳 Tarjeta</span><b id="cierreTarjeta">$0</b></div><div class="flex justify-between text-yellow-300"><span>🏦 Transfer</span><b id="cierreTransf">$0</b></div></div><div id="cierreDetalle" class="bg-gray-50 p-3 rounded-xl text-[11px]"></div></div><div class="grid grid-cols-2 gap-2 mt-4"><button onclick="imprimirCierre()" class="bg-black text-white py-3 rounded-xl font-black text-[12px]">🖨️ Imprimir</button><button onclick="enviarCierreWhatsApp()" class="bg-[#25D366] text-white py-3 rounded-xl font-black text-[12px]">📲 WhatsApp</button></div><button onclick="cerrarCierre()" class="w-full mt-2 bg-gray-100 py-3 rounded-xl font-bold">Cerrar</button></div></div>
<div class="fixed bottom-0 left-0 right-0 bg-white border-t flex justify-around py-2 max-w-md mx-auto z-30"><button onclick="showTab('costos')" class="flex flex-col items-center text-black"><i class="fa-solid fa-book"></i><span class="text-[7px]">Crear</span></button><button onclick="showTab('vender')" class="flex flex-col items-center text-gray-400"><i class="fa-solid fa-store"></i><span class="text-[7px]">Catalogo</span></button><button onclick="showTab('inventario')" class="flex flex-col items-center text-gray-400"><i class="fa-solid fa-boxes-stacked"></i><span class="text-[7px]">Invent</span></button><button onclick="showTab('finanzas')" class="flex flex-col items-center text-gray-400"><i class="fa-solid fa-chart-line"></i><span class="text-[7px]">Finanzas</span></button><button onclick="showTab('clientes')" class="flex flex-col items-center text-gray-400"><i class="fa-solid fa-users"></i><span class="text-[7px]">Clientes</span></button><button onclick="showTab('proveedores')" class="flex flex-col items-center text-gray-400"><i class="fa-solid fa-truck"></i><span class="text-[7px]">Prov</span></button></div></div></div>
<script src="https://unpkg.com/html5-qrcode@2.3.8/html5-qrcode.min.js"></script>
<script>
function exportarRespaldo(){let keys=['productosV2','inventarioMaestro','clientesV2','facturas','categoriasVenta','gastosFijos','empresaConfig','lotesMes','deudas','proveedores'];let data={_meta:{fecha:new Date().toISOString(), negocio:negocioId, user:currentUser, version:'11.6'}};keys.forEach(k=>{let v=localStorage.getItem(k+'_'+negocioId)||localStorage.getItem(k); if(v) data[k]=v;});let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});let url=URL.createObjectURL(blob);let a=document.createElement('a'); a.href=url; a.download='respaldo-11.6-'+getFechaSoloLocal()+'.json'; a.click();}
function importarRespaldo(input){let file=input.files[0]; if(!file) return;let reader=new FileReader();reader.onload=function(e){try{let data=JSON.parse(e.target.result);if(!confirm('¿Restaurar?')) return;let keys=['productosV2','inventarioMaestro','clientesV2','facturas','categoriasVenta','gastosFijos','empresaConfig','lotesMes','deudas','proveedores'];keys.forEach(k=>{if(data[k]) setItem(k,data[k]);});alert('✅ Restaurado'); location.reload();}catch(err){alert('Error:'+err.message);}};reader.readAsText(file);}
function buscarPorBarcode(codigo){if(!codigo) return;codigo=codigo.toString().trim().toLowerCase();let prods=getProd().filter(p=>!p.esBase);let encontrado=prods.find(p=> (p.codigoBarras && p.codigoBarras.toLowerCase()==codigo) || p.id==codigo);if(encontrado){addAlCarrito(encontrado.id); return;} alert('No encontrado: '+codigo);}
let html5QrcodeScanner=null;function iniciarScanner(){let el=document.getElementById('reader');el.classList.toggle('hidden');if(el.classList.contains('hidden')){if(html5QrcodeScanner){html5QrcodeScanner.clear();} return;}html5QrcodeScanner=new Html5Qrcode('reader');html5QrcodeScanner.start({facingMode:'environment'}, {fps:10, qrbox:250}, (decoded)=>{buscarPorBarcode(decoded);html5QrcodeScanner.stop(); el.classList.add('hidden');}, ()=>{});}
function descontarInventarioAuto(itemsVendidos){let inv=getInv();let prodList=getProd();let cambios=false;itemsVendidos.forEach(iv=>{let prod=prodList.find(p=>p.id==iv.idProducto);if(!prod) return;if(prod.bases && prod.bases.length){prod.bases.forEach(b=>{let base=prodList.find(x=>x.id==b.id);if(!base||!base.insumos) return;base.insumos.forEach(ins=>{let invItem=inv.find(x=>x.id==ins.invId);if(!invItem) return;let cu=parseFloat(ins.cu)||0;let uu=ins.uu||invItem.unidad;let cantDesc=convertir(cu, uu, invItem.unidad) * iv.qty;invItem.stock=(parseFloat(invItem.stock)||0)-cantDesc;if(invItem.stock<0) invItem.stock=0;cambios=true;});});}});if(cambios){setItem('inventarioMaestro',inv); renderInventarioMaster();}}
// --- resto de tu lógica 11.5 original ---
let carrito=[], fotoTemp='', logoTemp='', categoriaFiltro='todas', editId=null, currentUser=null, negocioId=null, ultimoTicket=null, ultimoCierre=null;
function getFechaLocal(){let now=new Date(); return now.toLocaleDateString('es-MX',{day:'2-digit',month:'2-digit',year:'numeric'})+', '+now.toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true});}
function getFechaSoloLocal(){let now=new Date(); return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;}
let fechaVista=new Date(), fechaSel=getFechaSoloLocal(), metodoPagoSel='Efectivo';
function setMetodoPago(m){metodoPagoSel=m; document.getElementById('metodoPago').value=m;}
function msgLogin(txt,ok){let el=document.getElementById('loginMsg'); el.innerText=txt; el.classList.remove('hidden');}
async function hacerRegistro(){let e=document.getElementById('loginEmail').value.trim().toLowerCase(); let p=document.getElementById('loginPass').value.trim(); let r=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:e,password:p})}); let j=await r.json(); alert(j.ok?'Creada':'Error');}
async function hacerLogin(){let e=document.getElementById('loginEmail').value.trim().toLowerCase(); let p=document.getElementById('loginPass').value.trim(); let r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:e,password:p})}); let j=await r.json(); if(!j.ok) return alert('Error'); currentUser=e; negocioId=j.negocio_id; localStorage.setItem('session_email',e); localStorage.setItem('session_negocio',negocioId); document.getElementById('loginScreen').classList.add('hidden'); await cargarDeNube(); showTab('inventario');}
function cerrarSesion(){localStorage.clear(); location.reload();}
async function cargarDeNube(){if(!currentUser) return; let r=await fetch('/api/load?email='+encodeURIComponent(currentUser)); let j=await r.json(); if(!j.ok) return; let data=j.data||{}; for(let k in data){ localStorage.setItem(k+'_'+negocioId, data[k]); } renderFijos(); renderInventario(); renderCategoriasVenta(); renderInventarioMaster(); renderProveedores();}
async function guardarEnNube(){if(!currentUser) return; let keys=['productosV2','inventarioMaestro','clientesV2','facturas','categoriasVenta','gastosFijos','empresaConfig','lotesMes','deudas','proveedores']; let data={}; keys.forEach(k=>{ let v=localStorage.getItem(k+'_'+negocioId) || localStorage.getItem(k); if(v) data[k]=v; }); await fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:currentUser,data})});}
window.addEventListener('load', async ()=>{ let e=localStorage.getItem('session_email'); let n=localStorage.getItem('session_negocio'); if(e&&n){ currentUser=e; negocioId=n; document.getElementById('loginScreen').classList.add('hidden'); await cargarDeNube(); showTab('inventario'); }});
function getFijos(){ return JSON.parse(localStorage.getItem('gastosFijos_'+negocioId)||'[]'); }
function getProd(){ return JSON.parse(localStorage.getItem('productosV2_'+negocioId)||'[]'); }
function getInv(){ return JSON.parse(localStorage.getItem('inventarioMaestro_'+negocioId)||'[]'); }
function getCli(){ return JSON.parse(localStorage.getItem('clientesV2_'+negocioId)||'[]'); }
function getFacts(){ return JSON.parse(localStorage.getItem('facturas_'+negocioId)||'[]'); }
function getDeudas(){ return JSON.parse(localStorage.getItem('deudas_'+negocioId)||'[]'); }
function getProveedores(){ return JSON.parse(localStorage.getItem('proveedores_'+negocioId)||'[]'); }
function getEmp(){ return JSON.parse(localStorage.getItem('empresaConfig_'+negocioId)||'{"nombre":"Mi Negocio"}'); }
function getCategoriasVenta(){ let cats=JSON.parse(localStorage.getItem('categoriasVenta_'+negocioId)||'[]'); if(!cats.length){ cats=[{id:'todas',nombre:'Todas'}]; } return cats; }
function setItem(k,v){ localStorage.setItem(k+'_'+negocioId, typeof v==='string'? v: JSON.stringify(v)); guardarEnNube(); }
function normalizarUnidad(u){ u=(u||'').toLowerCase().trim(); return u||'kg'; }
function factorABase(u){ let map={g:1,kg:1000,ml:1,L:1000,pza:1}; return map[normalizarUnidad(u)]||1; }
function convertir(cant, de, a){ return cant * factorABase(de) / factorABase(a); }
function parseCantidadTexto(texto, unidadBase){ if(!texto) return 0; let num=parseFloat(texto); if(isNaN(num)) return 0; return num; }
function addProveedor(){ let n=document.getElementById('provNombre').value.trim(); let provs=getProveedores(); provs.push({id:Date.now().toString(), nombre:n}); setItem('proveedores',provs); renderProveedores(); }
function renderProveedores(){ let provs=getProveedores(); let el=document.getElementById('listaProveedores'); if(!el) return; el.innerHTML=provs.map(p=>`<div>${p.nombre}</div>`).join(''); }
function addCategoriaVenta(){ let n=document.getElementById('nuevaCatNombre').value.trim(); if(!n) return; let cats=getCategoriasVenta(); cats.push({id:n+'-'+Date.now(),nombre:n}); setItem('categoriasVenta',cats); renderCategoriasVenta(); }
function renderCategoriasVenta(){ let cats=getCategoriasVenta(); let el=document.getElementById('filtrosCats'); if(el) el.innerHTML=cats.map(c=>`<button onclick="categoriaFiltro='${c.id}'; renderVenta();" class="px-4 py-2 rounded-full font-black text-[11px] border-2 ${categoriaFiltro==c.id?'bg-black text-white':'bg-white'}">${c.nombre}</button>`).join(''); }
function renderInventario(){ let prods=getProd(); let el=document.getElementById('listaInv'); if(el) el.innerHTML=prods.map(p=>`<div>${p.nombre} $${p.venta}</div>`).join(''); renderVenta(); }
function renderVenta(){ let prods=getProd().filter(p=>!p.esBase); let el=document.getElementById('listaVenta'); if(!el) return; el.innerHTML=prods.map(p=>`<div onclick="addAlCarrito('${p.id}')" class="bg-white rounded-[20px] p-3 border-2 border-black"><p class="font-black text-[12px]">${p.nombre}</p><p class="font-black text-[13px] text-green-600">$${(p.venta||0).toFixed(0)}</p><p class="text-[9px]">${p.codigoBarras||''}</p></div>`).join(''); }
function addAlCarrito(id){ let p=getProd().find(x=>x.id==id); if(!p) return; let ex=carrito.find(c=>c.id==id); if(ex) ex.qty++; else carrito.push({idProducto:id, id, nombre:p.nombre, venta:p.venta, qty:1}); renderCarrito(); }
function renderCarrito(){ let el=document.getElementById('ticket'); if(!carrito.length){ el.innerHTML='Vacío'; document.getElementById('c-total').innerText='0'; return; } let total=carrito.reduce((s,c)=>s+c.venta*c.qty,0); el.innerHTML=carrito.map(c=>`<div class="flex justify-between text-[12px]"><span>${c.nombre} x${c.qty}</span><span>$${(c.venta*c.qty).toFixed(0)}</span></div>`).join(''); document.getElementById('c-total').innerText=total.toFixed(0); }
function abrirCobro(){ if(!carrito.length) return; document.getElementById('cobroTotal').innerText=document.getElementById('c-total').innerText; document.getElementById('modalCobro').classList.remove('hidden'); }
function cerrarCobro(){ document.getElementById('modalCobro').classList.add('hidden'); }
function calcCambio(){ let total=parseFloat(document.getElementById('c-total').innerText)||0; let rec=parseFloat(document.getElementById('pagoRecibido').value)||0; document.getElementById('cambio').innerText=(rec-total).toFixed(2); }
function confirmarCobro(tipo){ let total=parseFloat(document.getElementById('c-total').innerText)||0; descontarInventarioAuto(carrito.map(c=>({idProducto:c.idProducto, qty:c.qty}))); let facts=getFacts(); facts.push({id:Date.now(),concepto:`Venta ${carrito.map(c=>c.nombre).join(', ')}`,monto:total,fecha:getFechaSoloLocal(),fechaHora:getFechaLocal(),tipo:'entrada',metodoPago:metodoPagoSel,vendedor:currentUser,items:carrito}); setItem('facturas',facts); carrito=[]; renderCarrito(); cerrarCobro(); renderCalendario(); alert('✅ Venta y stock descontado'); }
function showTab(t){ ['costos','vender','inventario','finanzas','clientes','config','proveedores'].forEach(x=>{ let el=document.getElementById('tab-'+x); if(el) el.classList.toggle('hidden',x!=t); }); if(t=='vender') renderVenta(); if(t=='inventario') renderInventarioMaster(); if(t=='finanzas') renderCalendario(); }
function renderInventarioMaster(){ let inv=getInv(); let el=document.getElementById('listaInvMaster'); if(el) el.innerHTML=inv.map(it=>`<div class="bg-gray-50 p-2 rounded-xl border">${it.nombre} Stock ${it.stock} ${it.unidad}</div>`).join(''); }
function renderCalendario(){ let facts=getFacts().filter(f=>f.vendedor==currentUser); let hoy=getFechaSoloLocal(); let factsHoy=facts.filter(f=>f.fecha==hoy); document.getElementById('fechaSelLabel').innerText=hoy; document.getElementById('labelTurno').innerText=currentUser; let entradas=factsHoy.filter(f=>f.tipo=='entrada').reduce((s,f)=>s+f.monto,0); document.getElementById('fin-balance').innerText='$'+entradas.toFixed(0); document.getElementById('flu-lista').innerHTML=factsHoy.map(f=>`<div>${f.concepto} $${f.monto}</div>`).join(''); }
function moverCal(dir){ renderCalendario(); }
function abrirCierre(){ let hoy=getFechaSoloLocal(); let facts=getFacts().filter(f=>f.fecha==hoy && f.vendedor==currentUser); let total=facts.filter(f=>f.tipo=='entrada').reduce((s,f)=>s+f.monto,0); document.getElementById('cierreFechaLabel').innerText=hoy; document.getElementById('cierreUserLabel').innerText=currentUser; document.getElementById('cierreTotal').innerText='$'+total.toFixed(0); document.getElementById('modalCierre').classList.remove('hidden'); }
function cerrarCierre(){ document.getElementById('modalCierre').classList.add('hidden'); }
function renderFijos(){}
function addFijo(){}
function addInsumo(){}
function calc(){}
function addBase(){}
function calc2(){}
function guardarProd(){}
function addInventario(){ let n=document.getElementById('inv-nombre').value.trim(); let p=parseFloat(document.getElementById('inv-precio').value)||0; let inv=getInv(); inv.push({id:Date.now().toString(),nombre:n,precio:p,stock:100,unidad:'kg'}); setItem('inventarioMaestro',inv); renderInventarioMaster(); }
function openGasto(){}
function setCrear(v){ document.getElementById('crear-menu').classList.toggle('hidden',v!='menu'); document.getElementById('crear-base').classList.toggle('hidden',v!='base'); document.getElementById('crear-producto').classList.toggle('hidden',v!='producto'); }
function cancelarEdicion(){ setCrear('menu'); }
</script></body></html>'''
if __name__=='__main__':
 app.run(host='0.0.0.0',port=5000)
