from flask import Flask
app = Flask(__name__)
@app.route('/')
def home():
 return """
<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mi Negocio 6.1 FIX</title><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"></head>
<body class="bg-[#FFF8F0] min-h-screen"><div class="max-w-md mx-auto pb-[90px]">
<div class="bg-white p-3 flex justify-between items-center sticky top-0 z-20 shadow-sm"><h1 class="font-black">Mi Negocio</h1><button onclick="tab('config')" class="text-[10px] bg-gray-100 px-3 py-1 rounded-full">Config</button></div>

<div id="p-costos" class="p-3">
<div class="bg-white rounded-[24px] p-4 shadow-sm">
<div class="flex gap-2 mb-2"><button id="bRec" onclick="setTipoCat('recetario')" class="flex-1 py-2.5 rounded-xl text-[11px] font-black bg-black text-white">RECETARIO</button><button id="bCat" onclick="setTipoCat('catalogo')" class="flex-1 py-2.5 rounded-xl text-[11px] font-black bg-gray-100">CATALOGO</button></div>
<input id="nombre" placeholder="Nombre" class="w-full border-2 p-3 rounded-xl font-bold text-sm"><textarea id="descripcion" placeholder="Descripcion" class="w-full border p-2 rounded-xl text-[11px] mt-2 h-12"></textarea><input id="prodImg" type="file" accept="image/*" class="text-[11px] mt-2"><img id="prevImg" class="w-20 h-20 rounded-xl object-cover mt-2 hidden">
<div id="insumos" class="mt-3 space-y-2"></div>
<div class="flex flex-col gap-2 mt-3"><div class="flex gap-2"><button onclick="addInsumo()" class="flex-1 text-[11px] bg-orange-100 py-2 rounded-full font-bold">+ Ingrediente</button><button id="btnBase" onclick="addInsumoSalsa()" class="flex-1 text-[11px] bg-amber-100 py-2 rounded-full font-bold">+ Del recetario</button></div><button id="btnComplemento" onclick="addInsumoCatalogo()" class="hidden text-[11px] bg-blue-100 py-2 rounded-full font-bold">+ Complemento</button></div>
<div class="mt-3 p-3 bg-gray-900 text-white rounded-xl text-[12px]">Costo $<span id="costo">0</span> | Venta $<span id="venta">0</span> <input id="margen" type="number" value="100" class="w-10 text-black rounded text-center text-[11px] ml-2">% | Fijos $<span id="c-fijos">0</span><br><input id="ventaManual" type="number" placeholder="Precio manual" class="w-full mt-2 text-black rounded px-2 py-1 text-[11px]" oninput="calc()"></div>
<button id="btnGuardar" onclick="guardar()" class="w-full mt-3 bg-black text-white py-3 rounded-xl font-black text-sm">Guardar</button><button id="btnCancelarEdit" onclick="cancelarEdit()" class="hidden w-full mt-2 bg-gray-100 py-2 rounded-xl text-[11px]">Cancelar</button>
</div><div id="listaInv" class="mt-4"></div>
</div>

<div id="p-vender" class="p-3 hidden"><div id="filtrosCat" class="flex gap-2 overflow-auto pb-2 mb-2"></div><div id="listaVenta" class="grid grid-cols-2 gap-3"></div>
<div class="mt-6 bg-white rounded-[20px] p-4 shadow-xl border"><h3 class="font-bold text-sm">Presupuesto <span id="c-count">0</span></h3><div id="c-items" class="text-[12px] mt-2"></div><select id="selCliente" class="w-full border p-2 rounded-xl text-sm mt-3"></select><div class="flex justify-between font-black text-lg mt-3">Total $<span id="c-total">0</span></div><button onclick="enviarPresupuesto()" class="w-full mt-3 bg-green-500 text-white py-3 rounded-xl font-black text-sm">WhatsApp</button><button onclick="cobrar()" class="w-full mt-2 bg-black text-white py-2 rounded-xl text-sm">Cobrar</button></div></div>

<div id="p-finanzas" class="p-3 hidden">
<div class="bg-[#2D3748] rounded-[20px] p-4 text-white"><div class="flex justify-between"><h2 class="font-black">Finanzas</h2><button onclick="openModalGasto()" class="bg-[#4FD1C5] text-black w-8 h-8 rounded-lg font-black">+</button></div><div class="grid grid-cols-3 gap-2 mt-3 text-center text-[10px]"><div class="bg-white/10 p-2 rounded-xl">HOY $<span id="f-flujoHoy">0</span></div><div class="bg-red-500/80 p-2 rounded-xl">POR PAGAR $<span id="f-porPagar">0</span></div><div class="bg-green-500 p-2 rounded-xl">VENCIDO $<span id="f-vencido">0</span></div></div><div class="mt-3 flex gap-1 overflow-auto"><button onclick="vistaFin='facturas';mostrarFinanzas()" id="vf-facturas" class="text-[10px] bg-white text-black px-3 py-1.5 rounded-full font-bold">Facturas</button><button onclick="vistaFin='proveedores';mostrarFinanzas()" id="vf-proveedores" class="text-[10px] bg-white/20 px-3 py-1.5 rounded-full">Proveedores</button><button onclick="vistaFin='categorias';mostrarFinanzas()" id="vf-categorias" class="text-[10px] bg-white/20 px-3 py-1.5 rounded-full">Cat. gastos</button></div></div>

<div id="view-facturas"><div id="f-lista" class="mt-3 bg-white rounded-2xl p-3 shadow-sm"></div></div>

<div id="view-proveedores" class="hidden"><div class="mt-3 bg-white rounded-2xl p-4 shadow-sm">
<div class="flex gap-2"><input id="provNombre" placeholder="Proveedor" class="flex-1 border-2 p-3 rounded-xl text-sm"><input id="provTel" placeholder="Tel" class="w-20 border-2 p-3 rounded-xl text-sm"><button onclick="addProveedorFix()" class="bg-black text-white px-5 rounded-xl font-black">+</button></div><div id="listaProveedores" class="mt-3"></div></div></div>

<div id="view-categorias" class="hidden"><div class="mt-3 bg-white rounded-2xl p-4 shadow-sm">
<h3 class="font-bold text-sm">Categorías de gastos - ILIMITADAS</h3><p class="text-[10px] text-gray-400 mb-3">Escribe y dale +. Las que tú quieras.</p>
<div class="flex gap-2"><input id="catGastoNombre" placeholder="Ej: Gasolina, Gas, Publicidad" class="flex-1 border-2 p-3 rounded-xl text-sm font-bold"><button onclick="addCatGastoFix()" class="bg-black text-white px-5 rounded-xl font-black text-xl">+</button></div>
<div id="listaCatGastos" class="mt-4 space-y-2"></div>
<div id="catMsg" class="hidden mt-3 text-[11px] bg-green-100 text-green-700 p-2 rounded-xl text-center"></div>
</div></div>

<div id="modalGasto" class="hidden fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4"><div class="bg-white w-full max-w-sm rounded-[24px] p-5"><h3 class="font-black text-sm">Nuevo gasto</h3><select id="g-tipo" class="w-full border-2 p-3 rounded-xl text-sm mt-3"><option value="salida">Salida</option><option value="entrada">Entrada</option></select><input id="g-concepto" placeholder="Concepto" class="w-full border p-3 rounded-xl text-sm mt-2"><input id="g-monto" type="number" placeholder="$ Monto" class="w-full border-2 p-3 rounded-xl text-sm mt-2"><div class="grid grid-cols-2 gap-2 mt-2"><select id="g-proveedor" class="border p-2 rounded-xl text-sm"></select><select id="g-catGasto" class="border p-2 rounded-xl text-sm"></select></div><input id="g-fecha" type="date" class="w-full border-2 p-3 rounded-xl text-sm mt-3"><div class="flex gap-2 mt-4"><button onclick="document.getElementById('modalGasto').classList.add('hidden')" class="flex-1 bg-gray-100 py-3 rounded-xl">Cancelar</button><button onclick="addFactura()" class="flex-1 bg-black text-white py-3 rounded-xl font-black">Guardar</button></div></div></div>
</div>

<div id="p-clientes" class="p-3 hidden"><div class="bg-white rounded-2xl p-4 shadow-sm"><input id="cliNombre" placeholder="Nombre" class="border p-3 rounded-xl text-sm w-full mb-2"><button onclick="addCliente()" class="bg-black text-white w-full py-3 rounded-xl font-bold text-sm">Guardar</button></div><div id="listaClientes" class="mt-3"></div></div>
<div id="p-config" class="p-3 hidden"><div class="bg-white rounded-2xl p-4 shadow-sm"><h2 class="font-black text-sm">Categorías productos</h2><div id="listaCats" class="mt-3"></div><div class="flex gap-2 mt-3"><input id="newCat" placeholder="Nueva" class="flex-1 border p-2.5 rounded-xl text-sm"><select id="newCatTipo" class="border p-2.5 rounded-xl text-sm"><option value="recetario">Recetario</option><option value="catalogo">Catalogo</option></select><button onclick="addCategoria()" class="bg-black text-white px-4 rounded-xl">+</button></div></div><div class="bg-white rounded-2xl p-4 shadow-sm mt-4"><div id="gastosFijos"></div><input id="prodMes" type="number" value="100" class="w-full border-2 p-3 rounded-xl mt-3 font-bold" oninput="calcGastosFijos()"><div class="mt-2 bg-black text-white p-3 rounded-xl text-center font-black">$<span id="cfg-porReceta">0</span> por producto</div></div></div>

<div class="fixed bottom-0 left-0 right-0 bg-white border-t flex justify-around py-2 max-w-md mx-auto z-30 text-gray-300">
<button onclick="tab('costos')" id="nav-costos" class="flex flex-col items-center text-black"><i class="fa-solid fa-book"></i><span class="text-[8px] font-bold">Crear</span></button>
<button onclick="tab('vender')" id="nav-vender" class="flex flex-col items-center"><i class="fa-solid fa-store"></i><span class="text-[8px]">Catalogo</span></button>
<button onclick="tab('finanzas')" id="nav-finanzas" class="flex flex-col items-center"><i class="fa-solid fa-chart-line"></i><span class="text-[8px]">Finanzas</span></button>
<button onclick="tab('clientes')" id="nav-clientes" class="flex flex-col items-center"><i class="fa-solid fa-users"></i><span class="text-[8px]">Clientes</span></button>
</div></div>
<script>
let tipoActual='recetario', editId=null, carrito=[], prodImgBase='', filtroTipo='todos', filtroFin='todos', subFin='todos', vistaFin='categorias'; const U=['kg','g','L','ml','galon','pza','cda'];
function baseFactor(u){ if(u=='kg'||u=='L') return 1000; if(u=='galon') return 3785; return 1;}
document.getElementById('prodImg').onchange=e=>{let r=new FileReader(); r.onload=()=>{prodImgBase=r.result; document.getElementById('prevImg').src=r.result; document.getElementById('prevImg').classList.remove('hidden');}; r.readAsDataURL(e.target.files[0]);};
function getCats(){let c=JSON.parse(localStorage.getItem('categoriasV2')||'null'); if(!c ||!c[0].grupo){c=[{id:'recetario',nombre:'Salsas / Bases',grupo:'recetario'},{id:'catalogo',nombre:'Platillos',grupo:'catalogo'}]; localStorage.setItem('categoriasV2',JSON.stringify(c));} return c;}
function saveCats(c){localStorage.setItem('categoriasV2',JSON.stringify(c)); renderCats(); renderCatBotones();}
function renderCats(){let cats=getCats(); let h=''; cats.forEach((cat,i)=>{h+=`<div class="flex gap-2 items-center bg-gray-50 p-2 rounded-xl"><input value="${cat.nombre}" onchange="let cs=getCats(); cs[${i}].nombre=this.value; saveCats(cs);" class="flex-1 bg-transparent font-bold text-sm outline-none"><span class="text-[9px] ${cat.grupo=='recetario'?'bg-amber-200':'bg-black text-white'} px-2 py-0.5 rounded-full">${cat.grupo}</span><button onclick="let cs=getCats(); cs.splice(${i},1); saveCats(cs);" class="text-red-300 px-2">x</button></div>`;}); let el=document.getElementById('listaCats'); if(el) el.innerHTML=h;}
function renderCatBotones(){let cats=getCats(); let sel=cats.find(c=>c.id==tipoActual) || cats[0]; if(sel) tipoActual=sel.id; let isRec=sel?.grupo=='recetario'; let bR=document.getElementById('bRec'); let bC=document.getElementById('bCat'); if(bR) bR.className=isRec?'flex-1 py-2.5 rounded-xl text-[11px] font-black bg-black text-white':'flex-1 py-2.5 rounded-xl text-[11px] font-black bg-gray-100'; if(bC) bC.className=!isRec?'flex-1 py-2.5 rounded-xl text-[11px] font-black bg-black text-white':'flex-1 py-2.5 rounded-xl text-[11px] font-black bg-gray-100'; let bc=document.getElementById('btnComplemento'); if(bc) bc.classList.toggle('hidden',isRec);}
function setTipoCat(g){let cats=getCats().filter(c=>c.grupo==g); if(cats.length) tipoActual=cats[0].id; renderCatBotones();}
function addCategoria(){let n=document.getElementById('newCat').value.trim(), g=document.getElementById('newCatTipo').value; if(!n) return; let cats=getCats(); cats.push({id:Date.now().toString(),nombre:n,grupo:g}); document.getElementById('newCat').value=''; saveCats(cats);}
function addInsumo(d={}){let div=document.createElement('div'); div.className='bg-[#FFF8F0] p-2 rounded-xl border text-[11px]'; div.dataset.tipo='ing'; div.innerHTML=`<div class="flex justify-between"><input placeholder="Ingrediente" value="${d.n||''}" class="in-n font-bold text-sm w-full bg-transparent outline-none"><button onclick="this.parentElement.parentElement.remove();calc()" class="text-red-300">x</button></div><div class="grid grid-cols-3 gap-1 mt-1"><input type="number" value="${d.cc||''}" placeholder="Cant" class="in-cc border p-2 rounded-lg" oninput="calc()"><select class="in-uc border p-2 rounded-lg" onchange="calc()">${U.map(x=>`<option ${d.uc==x?'selected':''}>${x}</option>`).join('')}</select><input type="number" value="${d.pc||''}" placeholder="$" class="in-pc border p-2 rounded-lg" oninput="calc()"><input type="number" value="${d.cu||''}" placeholder="Uso" class="in-cu border p-2 rounded-lg" oninput="calc()"><select class="in-uu border p-2 rounded-lg" onchange="calc()">${U.map(x=>`<option ${d.uu==x?'selected':''}>${x}</option>`).join('')}</select><div class="p-2 bg-white rounded-lg text-center font-bold">$<span class="in-sub">0</span></div></div>`; document.getElementById('insumos').appendChild(div);}
function addInsumoSalsa(){let bases=getCats().filter(c=>c.grupo=='recetario').map(c=>c.id); let salsas=getProd().filter(p=>bases.includes(p.tipo)); if(!salsas.length) return alert('Primero crea en RECETARIO'); let div=document.createElement('div'); div.className='bg-amber-50 p-2 rounded-xl border text-[11px]'; div.dataset.tipo='receta'; div.innerHTML=`<div class="flex justify-between"><span class="font-bold">Del recetario</span><button onclick="this.parentElement.parentElement.remove();calc()" class="text-red-300">x</button></div><div class="flex gap-1 mt-1"><select class="in-salsa border p-2 rounded-lg flex-1" onchange="calc()">${salsas.map(s=>`<option value="${s.id}" data-costo="${s.costo}" data-venta="${s.venta}">${s.nombre}</option>`).join('')}</select><input type="number" value="1" class="in-salsaCant w-16 border p-2 rounded-lg" oninput="calc()"><div class="p-2 bg-white rounded-lg font-bold">$<span class="in-sub">0</span></div></div>`; document.getElementById('insumos').appendChild(div); calc();}
function addInsumoCatalogo(){let prods=getProd(); if(!prods.length) return alert('No hay productos'); let div=document.createElement('div'); div.className='bg-blue-50 p-2 rounded-xl border text-[11px]'; div.dataset.tipo='catalogo'; div.innerHTML=`<div class="flex justify-between"><span class="font-bold">Complemento</span><button onclick="this.parentElement.parentElement.remove();calc()" class="text-red-300">x</button></div><div class="flex gap-1 mt-1"><select class="in-salsa border p-2 rounded-lg flex-1" onchange="calc()">${prods.map(s=>`<option value="${s.id}" data-costo="${s.costo}" data-venta="${s.venta}">${s.nombre}</option>`).join('')}</select><input type="number" value="1" class="in-salsaCant w-16 border p-2 rounded-lg" oninput="calc()"><div class="p-2 bg-white rounded-lg font-bold">$<span class="in-sub">0</span></div></div>`; document.getElementById('insumos').appendChild(div); calc();}
addInsumo({n:'Cebolla',cc:1,uc:'kg',pc:40,cu:150,uu:'g'});
function getProd(){return JSON.parse(localStorage.getItem('productosV2')||'[]');}
function calcGastosFijos(){let total=0; document.querySelectorAll('#gastosFijos > div').forEach(r=>{let m=r.querySelector('.gf-m'); if(m) total+=parseFloat(m.value)||0;}); let prodMes=parseFloat(document.getElementById('prodMes').value)||100; localStorage.setItem('prodMes',prodMes); let por=prodMes>0?total/prodMes:0; let el=document.getElementById('cfg-porReceta'); if(el) el.innerText=por.toFixed(2); let cf=document.getElementById('c-fijos'); if(cf) cf.innerText=por.toFixed(2); calc();}
function calc(){let tot=0; document.querySelectorAll('#insumos > div').forEach(row=>{let subEl=row.querySelector('.in-sub'); if(!subEl) return; if(row.dataset.tipo=='receta' || row.dataset.tipo=='catalogo'){let sel=row.querySelector('.in-salsa'); if(!sel ||!sel.options[sel.selectedIndex]) return; let costo=parseFloat(sel.options[sel.selectedIndex].dataset.costo)||0; if(row.dataset.tipo=='catalogo') costo=parseFloat(sel.options[sel.selectedIndex].dataset.venta)||costo; let cant=parseFloat(row.querySelector('.in-salsaCant').value)||0; let sub=costo*cant; subEl.innerText=sub.toFixed(2); tot+=sub;}else{let cc=parseFloat(row.querySelector('.in-cc').value)||0, pc=parseFloat(row.querySelector('.in-pc').value)||0, cu=parseFloat(row.querySelector('.in-cu').value)||0; if(!cc||!pc||!cu){subEl.innerText='0'; return;} let uc=row.querySelector('.in-uc').value, uu=row.querySelector('.in-uu').value; let cost=(pc/(cc*baseFactor(uc)))*(cu*baseFactor(uu)); if(uc=='pza'||uu=='pza') cost=(pc/cc)*cu; subEl.innerText=cost.toFixed(2); tot+=cost;}}); let ci=document.getElementById('c-ing'); if(ci) ci.innerText=tot.toFixed(2); let gf=parseFloat(document.getElementById('c-fijos')?.innerText||'0'); let ce=document.getElementById('costo'); if(ce) ce.innerText=(tot+gf).toFixed(2); let m=parseFloat(document.getElementById('margen').value)||0; let vm=document.getElementById('ventaManual').value; let ve=document.getElementById('venta'); if(ve){ if(vm && parseFloat(vm)>0) ve.innerText=parseFloat(vm).toFixed(2); else ve.innerText=((tot+gf)*(1+m/100)).toFixed(2);} }
document.getElementById('margen').oninput=calc;
function tab(t){['costos','vender','finanzas','clientes','config'].forEach(x=>{let el=document.getElementById('p-'+x); if(el) el.classList.toggle('hidden',x!=t);}); if(t=='vender') mostrarVenta(); if(t=='finanzas') mostrarFinanzas(); if(t=='clientes') mostrarClientes(); if(t=='config') renderCats();}
function getMovs(){return JSON.parse(localStorage.getItem('movs')||'[]');} function getClientes(){return JSON.parse(localStorage.getItem('clientes')||'[]');} function getFacturas(){return JSON.parse(localStorage.getItem('facturas')||'[]');} function getProveedores(){return JSON.parse(localStorage.getItem('proveedores')||'[]');} function getCatGastos(){let c=JSON.parse(localStorage.getItem('catGastos')||'[]'); if(!c.length){c=[{id:'renta',nombre:'Renta'},{id:'luz',nombre:'Luz / Agua'},{id:'insumos',nombre:'Insumos'},{id:'sueldos',nombre:'Sueldos'}]; localStorage.setItem('catGastos',JSON.stringify(c));} return c;}
function guardar(){let nombre=document.getElementById('nombre').value.trim(); if(!nombre) return alert('Nombre'); let desc=document.getElementById('descripcion').value; let costo=parseFloat(document.getElementById('costo').innerText), venta=parseFloat(document.getElementById('venta').innerText); let ings=[]; document.querySelectorAll('#insumos > div').forEach(row=>{if(row.dataset.tipo=='receta'||row.dataset.tipo=='catalogo'){ings.push({tipo:row.dataset.tipo,id:row.querySelector('.in-salsa').value,cant:row.querySelector('.in-salsaCant').value});} else {ings.push({tipo:'ing',n:row.querySelector('.in-n').value,cc:row.querySelector('.in-cc').value,uc:row.querySelector('.in-uc').value,pc:row.querySelector('.in-pc').value,cu:row.querySelector('.in-cu').value,uu:row.querySelector('.in-uu').value});}}); let p=getProd(); if(editId){let idx=p.findIndex(x=>x.id==editId); if(idx>=0){p[idx].nombre=nombre; p[idx].descripcion=desc; p[idx].costo=costo; p[idx].venta=venta; p[idx].tipo=tipoActual; p[idx].ingredientes=ings; if(prodImgBase) p[idx].img=prodImgBase;}} else {p.push({id:Date.now(),tipo:tipoActual,nombre,descripcion:desc,costo,venta,img:prodImgBase,ingredientes:ings});} localStorage.setItem('productosV2',JSON.stringify(p)); cancelarEdit();}
function editarProd(id){let p=getProd().find(x=>x.id==id); if(!p) return; editId=id; tipoActual=p.tipo; document.getElementById('nombre').value=p.nombre; document.getElementById('descripcion').value=p.descripcion||''; if(p.img){prodImgBase=p.img; let pi=document.getElementById('prevImg'); pi.src=p.img; pi.classList.remove('hidden');} document.getElementById('insumos').innerHTML=''; if(p.ingredientes){p.ingredientes.forEach(ing=>{if(ing.tipo=='ing') addInsumo({n:ing.n,cc:ing.cc,uc:ing.uc,pc:ing.pc,cu:ing.cu,uu:ing.uu}); else if(ing.tipo=='receta'){addInsumoSalsa(); let l=document.getElementById('insumos').lastElementChild; l.querySelector('.in-salsa').value=ing.id; l.querySelector('.in-salsaCant').value=ing.cant;} else if(ing.tipo=='catalogo'){addInsumoCatalogo(); let l=document.getElementById('insumos').lastElementChild; l.querySelector('.in-salsa').value=ing.id; l.querySelector('.in-salsaCant').value=ing.cant;}});} tab('costos'); renderCatBotones(); calc(); document.getElementById('btnCancelarEdit').classList.remove('hidden');}
function cancelarEdit(){editId=null; prodImgBase=''; document.getElementById('nombre').value=''; document.getElementById('descripcion').value=''; let pi=document.getElementById('prevImg'); if(pi) pi.classList.add('hidden'); document.getElementById('insumos').innerHTML=''; document.getElementById('ventaManual').value=''; document.getElementById('btnCancelarEdit').classList.add('hidden'); addInsumo({}); calc(); mostrar();}
function mostrar(){let prods=getProd(); let cats=getCats(); let h=''; prods.forEach((p,i)=>{let cat=cats.find(c=>c.id==p.tipo); h+=`<div class="bg-white p-2 rounded-xl flex gap-2 shadow-sm mt-2 items-center"><span class="text-[8px] bg-gray-100 px-2 py-1 rounded-full">${cat?cat.nombre:p.tipo}</span><div class="flex-1"><b class="text-[12px]">${p.nombre}</b><br><span class="text-[10px]">$${p.costo.toFixed(2)} → $${p.venta.toFixed(2)}</span></div><button onclick="editarProd(${p.id})" class="bg-blue-50 text-blue-600 px-2 py-1 rounded-full text-[10px]">Editar</button><button onclick="let pr=getProd(); pr.splice(${i},1); localStorage.setItem('productosV2',JSON.stringify(pr)); mostrar();" class="text-red-300">X</button></div>`;}); document.getElementById('listaInv').innerHTML=h; mostrarVenta();}
function mostrarVenta(){let prods=getProd().filter(p=>{let c=getCats().find(cat=>cat.id==p.tipo); return c && c.grupo=='catalogo';}); let h=''; prods.forEach(p=>{h+=`<div class="bg-white rounded-2xl shadow-sm border overflow-hidden"><button onclick="addCart(${p.id})" class="w-full text-left"><img src="${p.img||'https://via.placeholder.com/200'}" class="w-full h-24 object-cover"><div class="p-2"><b class="text-[11px]">${p.nombre}</b><p class="text-[11px] text-green-600 font-bold">$${p.venta.toFixed(2)}</p></div></button><div class="px-2 pb-2"><button onclick="editarProd(${p.id})" class="w-full text-[9px] bg-blue-50 py-1 rounded-full">Editar precio</button></div></div>`;}); let lv=document.getElementById('listaVenta'); if(lv) lv.innerHTML=h||'<p class="text-sm text-gray-400">Sin productos catalogo</p>';}
function addCart(id){let p=getProd().find(x=>x.id==id); let ex=carrito.find(x=>x.id==id); if(ex) ex.qty++; else carrito.push({...p,qty:1}); let t=0,c=0,html=''; carrito.forEach(x=>{t+=x.venta*x.qty; c+=x.qty; html+=`<div class="flex justify-between py-1 text-[12px]"><span>${x.nombre} x${x.qty}</span><span>$${(x.venta*x.qty).toFixed(0)}</span></div>`;}); document.getElementById('c-total').innerText=t.toFixed(0); document.getElementById('c-count').innerText=c; document.getElementById('c-items').innerHTML=html||'Vacio';}
function cobrar(){if(!carrito.length) return; let total=parseFloat(document.getElementById('c-total').innerText); let movs=getMovs(); movs.unshift({tipo:'entrada',concepto:'Venta',monto:total,fecha:new Date().toLocaleDateString()}); localStorage.setItem('movs',JSON.stringify(movs)); carrito=[]; document.getElementById('c-total').innerText='0'; document.getElementById('c-count').innerText='0'; document.getElementById('c-items').innerHTML='Vacio'; tab('finanzas');}
function enviarPresupuesto(){let texto=`*PRESUPUESTO*%0A`; carrito.forEach(p=>texto+=`• ${p.nombre} x${p.qty} $${(p.venta*p.qty).toFixed(2)}%0A`); window.open('https://wa.me/?text='+texto,'_blank');}
function addCliente(){let n=document.getElementById('cliNombre').value; if(!n) return; let cli=getClientes(); cli.push({id:Date.now().toString(),nombre:n}); localStorage.setItem('clientes',JSON.stringify(cli)); mostrarClientes();}
function mostrarClientes(){let cli=getClientes(); let h=''; cli.forEach((c,i)=>h+=`<div class="bg-white p-3 rounded-xl flex justify-between shadow-sm"><b class="text-[12px]">${c.nombre}</b><button onclick="let cl=getClientes(); cl.splice(${i},1); localStorage.setItem('clientes',JSON.stringify(cl)); mostrarClientes();" class="text-red-300">X</button></div>`); document.getElementById('listaClientes').innerHTML=h;}
function openModalGasto(){let provs=getProveedores(); let cats=getCatGastos(); let selP=document.getElementById('g-proveedor'); let selC=document.getElementById('g-catGasto'); if(selP) selP.innerHTML='<option value="">Sin proveedor</option>'+provs.map(p=>`<option value="${p.id}">${p.nombre}</option>`).join(''); if(selC) selC.innerHTML='<option value="">Sin categoria</option>'+cats.map(c=>`<option value="${c.id}">${c.nombre}</option>`).join(''); document.getElementById('modalGasto').classList.remove('hidden');}
function addFactura(){let concepto=document.getElementById('g-concepto').value.trim(), monto=parseFloat(document.getElementById('g-monto').value), fecha=document.getElementById('g-fecha').value; if(!concepto||!monto||!fecha) return alert('Faltan datos'); let facts=getFacturas(); facts.push({id:Date.now(),concepto,monto,fecha,fechaObj:new Date(fecha+'T00:00:00').getTime(),tipo:document.getElementById('g-tipo').value,proveedorId:document.getElementById('g-proveedor').value,catGastoId:document.getElementById('g-catGasto').value,estado:'pendiente'}); localStorage.setItem('facturas',JSON.stringify(facts)); document.getElementById('modalGasto').classList.add('hidden'); mostrarFinanzas();}

// --- FIX CATEGORIAS ILIMITADAS ---
function addCatGastoFix(){
  let input=document.getElementById('catGastoNombre');
  let n=input.value.trim();
  if(!n){ alert('Escribe una categoria primero'); input.focus(); return; }
  let cats=getCatGastos();
  // evitar duplicados
  if(cats.some(c=>c.nombre.toLowerCase()===n.toLowerCase())){ alert('Esa categoria ya existe'); return; }
  cats.push({id:Date.now().toString(), nombre:n});
  localStorage.setItem('catGastos', JSON.stringify(cats));
  input.value='';
  let msg=document.getElementById('catMsg');
  msg.innerText='✅ Categoria "'+n+'" agregada';
  msg.classList.remove('hidden');
  setTimeout(()=>msg.classList.add('hidden'),2000);
  mostrarFinanzas();
}
function addProveedorFix(){
  let inputN=document.getElementById('provNombre');
  let inputT=document.getElementById('provTel');
  let n=inputN.value.trim();
  if(!n){ alert('Escribe nombre proveedor'); inputN.focus(); return; }
  let provs=getProveedores();
  provs.push({id:Date.now().toString(), nombre:n, tel:inputT.value.trim()});
  localStorage.setItem('proveedores', JSON.stringify(provs));
  inputN.value=''; inputT.value='';
  mostrarFinanzas();
}
function mostrarFinanzas(){
  let facts=getFacturas(); let provs=getProveedores(); let cats=getCatGastos();
  let vfF=document.getElementById('view-facturas'), vp=document.getElementById('view-proveedores'), vc=document.getElementById('view-categorias');
  if(vfF) vfF.classList.toggle('hidden',vistaFin!='facturas');
  if(vp) vp.classList.toggle('hidden',vistaFin!='proveedores');
  if(vc) vc.classList.toggle('hidden',vistaFin!='categorias');
  document.getElementById('vf-facturas').className=vistaFin=='facturas'?'text-[10px] bg-white text-black px-3 py-1.5 rounded-full font-bold':'text-[10px] bg-white/20 px-3 py-1.5 rounded-full';
  document.getElementById('vf-proveedores').className=vistaFin=='proveedores'?'text-[10px] bg-white text-black px-3 py-1.5 rounded-full font-bold':'text-[10px] bg-white/20 px-3 py-1.5 rounded-full';
  document.getElementById('vf-categorias').className=vistaFin=='categorias'?'text-[10px] bg-white text-black px-3 py-1.5 rounded-full font-bold':'text-[10px] bg-white/20 px-3 py-1.5 rounded-full';
  // render categorias
  if(vistaFin=='categorias'){
    let h=''; cats.forEach((c,i)=>{
      let total=facts.filter(f=>f.catGastoId==c.id).reduce((s,f)=>s+f.monto,0);
      h+=`<div class="flex justify-between items-center bg-gray-50 p-3 rounded-xl"><div><b class="text-[13px]">${c.nombre}</b><br><span class="text-[10px] text-gray-400">Gastado: $${total.toFixed(0)} • ID: ${c.id.slice(-4)}</span></div><div class="flex gap-2"><button onclick="let cs=getCatGastos(); let nuevo=prompt('Editar nombre:',cs[${i}].nombre); if(nuevo){cs[${i}].nombre=nuevo.trim(); localStorage.setItem('catGastos',JSON.stringify(cs)); mostrarFinanzas();}" class="text-blue-500 text-[11px] font-bold">Editar</button><button onclick="if(confirm('Borrar ${c.nombre}?')){let cs=getCatGastos(); cs.splice(${i},1); localStorage.setItem('catGastos',JSON.stringify(cs)); mostrarFinanzas();}" class="text-red-300 font-bold">X</button></div></div>`;
    });
    document.getElementById('listaCatGastos').innerHTML=h||'<p class="text-[11px] text-gray-400">Sin categorias, agrega la primera arriba</p>';
  }
  if(vistaFin=='proveedores'){
    let h=''; provs.forEach((p,i)=>{h+=`<div class="flex justify-between items-center bg-gray-50 p-3 rounded-xl mt-2"><div><b class="text-[13px]">${p.nombre}</b><br><span class="text-[10px] text-gray-400">${p.tel||''}</span></div><button onclick="let pr=getProveedores(); pr.splice(${i},1); localStorage.setItem('proveedores',JSON.stringify(pr)); mostrarFinanzas();" class="text-red-300">X</button></div>`;});
    document.getElementById('listaProveedores').innerHTML=h||'<p class="text-[11px] text-gray-400">Sin proveedores</p>';
  }
  if(vistaFin=='facturas'){
    let h=''; facts.slice().reverse().forEach(f=>{let cat=cats.find(c=>c.id==f.catGastoId); h+=`<div class="flex justify-between py-2 border-b"><div><p class="text-[12px] font-bold">${f.concepto}</p><p class="text-[10px] text-gray-400">${cat?cat.nombre:''} • ${f.fecha}</p></div><b>$${f.monto}</b></div>`;});
    document.getElementById('f-lista').innerHTML=h||'<p class="text-[11px] text-gray-400 py-6 text-center">Sin facturas, dale + arriba</p>';
  }
  // totales
  let porPagar=0,vencido=0; let hoy=new Date(); hoy.setHours(0,0,0,0); let hoyTime=hoy.getTime();
  facts.forEach(f=>{if(f.estado=='pendiente' && f.tipo=='salida'){porPagar+=f.monto; if(f.fechaObj<hoyTime) vencido+=f.monto;}});
  document.getElementById('f-porPagar').innerText=porPagar.toFixed(0); document.getElementById('f-vencido').innerText=vencido.toFixed(0);
}
document.getElementById('catGastoNombre').addEventListener('keypress',function(e){ if(e.key==='Enter'){ addCatGastoFix(); } });
document.getElementById('provNombre').addEventListener('keypress',function(e){ if(e.key==='Enter'){ addProveedorFix(); } });
let sGF=JSON.parse(localStorage.getItem('gastosFijos')||'[]'); let prodMesEl=document.getElementById('prodMes'); if(prodMesEl) prodMesEl.value=localStorage.getItem('prodMes')||100; let today=new Date().toISOString().split('T')[0]; let gf=document.getElementById('g-fecha'); if(gf) gf.value=today; renderCats(); renderCatBotones(); calcGastosFijos(); calc(); mostrar(); mostrarClientes(); mostrarFinanzas();
</script></body></html>
"""
