from flask import Flask
app = Flask(__name__)
@app.route('/')
def home():
 return """
<!DOCTYPE html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mi Negocio 8.0 Flujo</title><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<style>input,select,textarea{color:#000!important; background:#fff!important;}</style></head>
<body class="bg-[#FFF8F0] min-h-screen"><div class="max-w-md mx-auto pb-[95px]">
<div class="bg-white p-3 flex justify-between items-center sticky top-0 z-20 shadow-sm"><h1 class="font-black">Mi Negocio</h1><button onclick="tab('config')" class="text-[10px] bg-gray-100 px-3 py-1 rounded-full">Config</button></div>

<div id="p-costos" class="p-3 hidden">
<div class="bg-white rounded-[28px] p-4 shadow-sm">
<div class="flex gap-2 mb-2"><button id="bRec" onclick="setTipoCat('recetario')" class="flex-1 py-3 rounded-2xl text-[11px] font-black bg-black text-white">RECETARIO</button><button id="bCat" onclick="setTipoCat('catalogo')" class="flex-1 py-3 rounded-2xl text-[11px] font-black bg-gray-100">CATALOGO</button></div>
<input id="nombre" placeholder="Masa de crepas" class="w-full border-2 border-black p-4 rounded-2xl font-bold text-[15px]"><div id="insumos" class="mt-4 space-y-3"></div>
<div class="flex gap-2 mt-4"><button onclick="addInsumo()" class="flex-1 text-[11px] bg-orange-100 py-3 rounded-full font-black">+ Ingrediente</button><button onclick="addInsumoSalsa()" class="flex-1 text-[11px] bg-amber-200 py-3 rounded-full font-black">+ Del recetario</button></div>
<button id="btnComplemento" onclick="addInsumoCatalogo()" class="hidden w-full text-[11px] bg-blue-100 py-3 rounded-full font-black mt-2">+ Complemento</button>
<div class="mt-4 p-4 bg-[#0F172A] text-white rounded-[16px] text-[13px]"><div class="flex justify-between"><span>Ingredientes</span><b>$<span id="c-ing">0</span></b></div><div class="flex justify-between text-amber-300"><span>+ Fijos auto</span><b>$<span id="c-fijos">0</span></b></div><div class="flex justify-between font-black text-[15px] border-t mt-2 pt-2">Costo $<span id="costo">0</span> | Venta $<span id="venta">0</span></div><div class="mt-2 flex gap-2"><span class="text-[10px] opacity-70">Margen</span><input id="margen" type="number" value="100" class="w-14 text-black rounded text-center font-black py-1" oninput="calc()"><input id="ventaManual" type="number" placeholder="$ final" class="ml-auto w-20 text-black rounded px-2 py-1 font-black text-[12px]" oninput="calc()"></div></div>
<button onclick="guardar()" class="w-full mt-4 bg-black text-white py-4 rounded-2xl font-black">Guardar</button><button id="btnCancelarEdit" onclick="cancelarEdit()" class="hidden w-full mt-2 bg-gray-100 py-3 rounded-2xl text-[11px]">Cancelar</button>
</div><div id="listaInv" class="mt-5"></div>
</div>

<div id="p-vender" class="p-3 hidden"><div id="listaVenta" class="grid grid-cols-2 gap-3"></div><div class="mt-6 bg-white rounded-[20px] p-4 shadow-xl border"><div class="flex justify-between font-black text-lg">Total $<span id="c-total">0</span></div><button onclick="cobrar()" class="w-full mt-2 bg-black text-white py-3 rounded-xl font-black">Cobrar y mandar a flujo</button></div></div>

<div id="p-finanzas" class="p-3">
<div class="bg-[#2D3748] rounded-[24px] p-4 text-white">
<div class="flex justify-between items-center"><h2 class="font-black text-[16px]">Finanzas</h2><button onclick="openModalGasto()" class="bg-[#4FD1C5] text-black w-9 h-9 rounded-xl font-black text-[20px]">+</button></div>
<div class="mt-4 grid grid-cols-5 gap-1.5 overflow-auto"><button onclick="vistaFin='flujo';mostrarFinanzas()" id="vf-flujo" class="text-[9px] px-2 py-2 rounded-full whitespace-nowrap font-black">📊 Flujo</button><button onclick="vistaFin='facturas';mostrarFinanzas()" id="vf-facturas" class="text-[9px] px-2 py-2 rounded-full whitespace-nowrap">Facturas</button><button onclick="vistaFin='proveedores';mostrarFinanzas()" id="vf-proveedores" class="text-[9px] px-2 py-2 rounded-full whitespace-nowrap">Provee.</button><button onclick="vistaFin='categorias';mostrarFinanzas()" id="vf-categorias" class="text-[9px] px-2 py-2 rounded-full whitespace-nowrap">Cat.</button><button onclick="vistaFin='fijos';mostrarFinanzas()" id="vf-fijos" class="text-[9px] px-2 py-2 rounded-full whitespace-nowrap">Fijos</button></div>
</div>

<!-- FLUJO DE CAJA -->
<div id="view-flujo" class="">
<div class="mt-3 bg-white rounded-[20px] p-4 shadow-sm">
<div class="flex justify-between items-center"><h3 class="font-black text-[14px]">📊 Flujo de caja</h3><input id="mesFlujo" type="month" class="border-2 border-black rounded-xl px-2 py-1 text-[12px] font-bold" onchange="mostrarFinanzas()"></div>
<div class="grid grid-cols-3 gap-2 mt-4 text-center">
<div class="bg-green-50 border-2 border-green-200 rounded-2xl p-3"><p class="text-[9px] font-black text-green-700">ENTRADAS</p><p class="font-black text-[16px] text-green-600">$<span id="flujo-entradas">0</span></p><p class="text-[8px] text-gray-500" id="flujo-det-entradas">0 ventas</p></div>
<div class="bg-red-50 border-2 border-red-200 rounded-2xl p-3"><p class="text-[9px] font-black text-red-700">SALIDAS</p><p class="font-black text-[16px] text-red-600">$<span id="flujo-salidas">0</span></p><p class="text-[8px] text-gray-500" id="flujo-det-salidas">0 gastos</p></div>
<div class="bg-black text-white rounded-2xl p-3"><p class="text-[9px] font-black opacity-70">GANANCIA</p><p class="font-black text-[16px] text-[#4FD1C5]">$<span id="flujo-ganancia">0</span></p><p class="text-[8px] opacity-70" id="flujo-porc">0%</p></div>
</div>
<div class="mt-4">
<div class="w-full bg-gray-100 rounded-full h-4 flex overflow-hidden"><div id="flujo-bar-entradas" class="bg-green-500 h-4" style="width:50%"></div><div id="flujo-bar-salidas" class="bg-red-500 h-4" style="width:50%"></div></div>
<div class="flex justify-between text-[9px] mt-1 font-bold"><span class="text-green-600">Entradas</span><span class="text-red-600">Salidas</span></div>
</div>
<div id="flujo-lista" class="mt-4 space-y-1 max-h-[350px] overflow-auto"></div>
</div>
</div>

<div id="view-facturas" class="hidden"><div id="f-lista" class="mt-3 bg-white rounded-2xl p-3"></div></div>
<div id="view-proveedores" class="hidden"><div class="mt-3 bg-white rounded-2xl p-4"><div class="flex gap-2"><input id="provNombre" placeholder="Proveedor" class="flex-1 border-2 p-3 rounded-xl font-bold"><button onclick="addProveedorFix()" class="bg-black text-white px-5 rounded-xl">+</button></div><div id="listaProveedores" class="mt-3"></div></div></div>
<div id="view-categorias" class="hidden"><div class="mt-3 bg-white rounded-[20px] p-4"><div class="flex gap-2"><input id="catGastoNombre" placeholder="Ej: Gasolina" class="flex-1 border-2 border-black p-4 rounded-2xl font-bold"><button onclick="addCatGastoFix()" class="bg-black text-white px-6 rounded-2xl">+</button></div><button onclick="addCatGastoFix()" class="w-full mt-2 bg-black text-white py-3 rounded-2xl font-black">GUARDAR</button><div id="catMsg" class="hidden mt-3 p-3 rounded-xl text-center font-bold"></div><div id="listaCatGastos" class="mt-4 space-y-2"></div></div></div>
<div id="view-fijos" class="hidden"><div class="mt-3 bg-white rounded-[20px] p-4"><h3 class="font-black text-[14px]">Gastos fijos</h3><input id="prodMes" type="number" value="100" class="w-full border-2 border-black p-3 rounded-xl mt-2 font-black" oninput="calcGastosFijos()"><div id="gastosFijos" class="mt-3 space-y-2"></div><button onclick="addGastoFijo({})" class="w-full mt-3 bg-gray-100 py-3 rounded-full text-[11px] font-black">+ Agregar</button><div class="mt-3 bg-black text-white p-4 rounded-2xl text-center">Total mes $<span id="totalFijosMes">0</span> | Por receta $<span id="cfg-porReceta">0</span><span class="hidden" id="f-fijoPorReceta">0</span></div></div></div>

<div id="modalGasto" class="hidden fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4"><div class="bg-white w-full max-w-sm rounded-[24px] p-5"><h3 class="font-black text-sm">Nuevo movimiento</h3><select id="g-tipo" class="w-full border-2 p-3 rounded-xl mt-3 font-bold"><option value="salida">🔴 Salida (gasto)</option><option value="entrada">🟢 Entrada (ingreso extra)</option></select><input id="g-concepto" placeholder="Concepto Ej: Renta, Venta extra" class="w-full border-2 p-3 rounded-xl mt-2 font-bold"><input id="g-monto" type="number" placeholder="$ Monto" class="w-full border-2 p-3 rounded-xl mt-2 font-black text-[16px]"><div class="grid grid-cols-2 gap-2 mt-2"><select id="g-proveedor" class="border-2 p-2 rounded-xl text-[12px]"></select><select id="g-catGasto" class="border-2 p-2 rounded-xl text-[12px]"></select></div><input id="g-fecha" type="date" class="w-full border-2 p-3 rounded-xl mt-2 font-bold"><div class="flex gap-2 mt-4"><button onclick="document.getElementById('modalGasto').classList.add('hidden')" class="flex-1 bg-gray-100 py-3 rounded-xl font-bold">Cerrar</button><button onclick="addFactura()" class="flex-1 bg-black text-white py-3 rounded-xl font-black">Guardar</button></div></div></div>
</div>

<div id="p-clientes" class="p-3 hidden"><div id="listaClientes"></div></div>
<div id="p-config" class="p-3 hidden"><div id="listaCats"></div><input id="newCat" placeholder="Nueva" class="w-full border-2 p-3 rounded-xl mt-2"><select id="newCatTipo" class="w-full border-2 p-3 rounded-xl mt-2"><option value="recetario">Recetario</option><option value="catalogo">Catalogo</option></select><button onclick="addCategoria()" class="w-full mt-2 bg-black text-white py-3 rounded-xl">+ Agregar</button></div>

<div class="fixed bottom-0 left-0 right-0 bg-white border-t flex justify-around py-2 max-w-md mx-auto z-30">
<button onclick="tab('costos')" id="nav-costos" class="flex flex-col items-center text-gray-400"><i class="fa-solid fa-book"></i><span class="text-[8px]">Crear</span></button>
<button onclick="tab('vender')" id="nav-vender" class="flex flex-col items-center text-gray-400"><i class="fa-solid fa-store"></i><span class="text-[8px]">Catalogo</span></button>
<button onclick="tab('finanzas')" id="nav-finanzas" class="flex flex-col items-center text-black"><i class="fa-solid fa-chart-line"></i><span class="text-[8px] font-bold">Finanzas</span></button>
<button onclick="tab('clientes')" id="nav-clientes" class="flex flex-col items-center text-gray-400"><i class="fa-solid fa-users"></i><span class="text-[8px]">Clientes</span></button>
</div></div>

<script>
let tipoActual='recetario', editId=null, carrito=[], prodImgBase='', vistaFin='flujo'; const U=['kg','g','L','ml','galon','pza','cda'];
function baseFactor(u){ if(u=='kg'||u=='L') return 1000; if(u=='galon') return 3785; return 1;}
function getCats(){let c=JSON.parse(localStorage.getItem('categoriasV2')||'[]'); if(!c.length){c=[{id:'recetario',nombre:'Masa base',grupo:'recetario'},{id:'catalogo',nombre:'Crepas',grupo:'catalogo'}]; localStorage.setItem('categoriasV2',JSON.stringify(c));} return c;}
function getProd(){return JSON.parse(localStorage.getItem('productosV2')||'[]');}
function getGF(){return JSON.parse(localStorage.getItem('gastosFijos')||'[]');}
function getFacturas(){return JSON.parse(localStorage.getItem('facturas')||'[]');}
function getMovs(){return JSON.parse(localStorage.getItem('movs')||'[]');}
function getProveedores(){return JSON.parse(localStorage.getItem('proveedores')||'[]');}
function getCatGastos(){let c=JSON.parse(localStorage.getItem('catGastos')||'[]'); if(!c.length){c=[{id:'renta',nombre:'Renta'},{id:'luz',nombre:'Luz / Agua'}]; localStorage.setItem('catGastos',JSON.stringify(c));} return c;}
function addInsumo(d={}){let div=document.createElement('div'); div.className='bg-[#FFF8F0] p-3 rounded-[16px] border-2'; div.dataset.tipo='ing'; div.innerHTML=`<div class="flex justify-between mb-2"><input placeholder="Ingrediente" value="${d.n||''}" class="in-n font-black text-[13px] w-full bg-transparent"><button onclick="this.closest('div').parentElement.remove();calc()" class="text-red-400">x</button></div><div class="bg-white rounded-xl p-2 grid grid-cols-3 gap-2"><input type="number" value="${d.cc||''}" placeholder="Cant" class="in-cc border-2 p-2 rounded-lg" oninput="calc()"><select class="in-uc border-2 p-2 rounded-lg" onchange="calc()">${U.map(x=>`<option ${d.uc==x?'selected':''}>${x}</option>`).join('')}</select><input type="number" value="${d.pc||''}" placeholder="$" class="in-pc border-2 p-2 rounded-lg" oninput="calc()"><input type="number" value="${d.cu||''}" placeholder="Uso" class="in-cu border-2 border-black p-2 rounded-lg" oninput="calc()"><select class="in-uu border-2 border-black p-2 rounded-lg" onchange="calc()">${U.map(x=>`<option ${d.uu==x?'selected':''}>${x}</option>`).join('')}</select><div class="bg-black text-white rounded-lg p-2 text-center font-black">$<span class="in-sub">0.00</span></div></div>`; document.getElementById('insumos').appendChild(div);}
function addInsumoSalsa(){let bases=getCats().filter(c=>c.grupo=='recetario').map(c=>c.id); let salsas=getProd().filter(p=>bases.includes(p.tipo)); if(!salsas.length) return alert('Crea recetario primero'); let div=document.createElement('div'); div.className='bg-amber-50 p-3 rounded-[16px] border-2'; div.dataset.tipo='receta'; div.innerHTML=`<div class="flex justify-between"><span class="font-black text-[11px]">📖 Del recetario</span><button onclick="this.parentElement.parentElement.remove();calc()" class="text-red-400">x</button></div><div class="grid grid-cols-4 gap-2 mt-2 bg-white p-2 rounded-xl"><select class="in-salsa col-span-3 border-2 p-2 rounded-lg text-[12px]" onchange="calc()">${salsas.map(s=>`<option value="${s.id}" data-costo="${s.costo}">${s.nombre}</option>`).join('')}</select><input type="number" value="1" class="in-salsaCant border-2 p-2 rounded-lg" oninput="calc()"><div class="col-span-4 text-right font-black">$<span class="in-sub">0.00</span></div></div>`; document.getElementById('insumos').appendChild(div); calc();}
function addInsumoCatalogo(){let prods=getProd(); if(!prods.length) return alert('No hay'); let div=document.createElement('div'); div.className='bg-blue-50 p-3 rounded-[16px] border-2'; div.dataset.tipo='catalogo'; div.innerHTML=`<div class="flex justify-between"><span class="font-black text-[11px]">🛒 Complemento</span><button onclick="this.parentElement.parentElement.remove();calc()" class="text-red-400">x</button></div><div class="grid grid-cols-4 gap-2 mt-2 bg-white p-2 rounded-xl"><select class="in-salsa col-span-3 border-2 p-2 rounded-lg text-[12px]" onchange="calc()">${prods.map(s=>`<option value="${s.id}" data-costo="${s.costo}" data-venta="${s.venta}">${s.nombre} $${s.venta.toFixed(2)}</option>`).join('')}</select><input type="number" value="1" class="in-salsaCant border-2 p-2 rounded-lg" oninput="calc()"><div class="col-span-4 text-right font-black">$<span class="in-sub">0.00</span></div></div>`; document.getElementById('insumos').appendChild(div); calc();}
function addGastoFijo(d={}){let div=document.createElement('div'); div.className='flex gap-2 items-center bg-gray-50 p-2 rounded-xl border'; div.innerHTML=`<input value="${d.nombre||''}" placeholder="Ej: Renta" class="gf-n flex-1 bg-transparent font-bold text-[13px] p-2 outline-none" oninput="calcGastosFijos()"><input type="number" value="${d.monto||''}" placeholder="$" class="gf-m w-28 border-2 border-black p-2.5 rounded-xl font-black text-[14px]" oninput="calcGastosFijos()"><button onclick="this.parentElement.remove();calcGastosFijos()" class="text-red-400 w-8 h-8 rounded-full font-black">X</button>`; document.getElementById('gastosFijos').appendChild(div);}
function calcGastosFijos(){let total=0, arr=[]; document.querySelectorAll('#gastosFijos > div').forEach(r=>{let n=r.querySelector('.gf-n')?.value||''; let m=parseFloat(r.querySelector('.gf-m')?.value)||0; if(n||m){arr.push({nombre:n,monto:m}); total+=m;}}); localStorage.setItem('gastosFijos',JSON.stringify(arr)); let prodMes=parseFloat(document.getElementById('prodMes').value)||100; localStorage.setItem('prodMes',prodMes); let por=prodMes>0?total/prodMes:0; document.getElementById('totalFijosMes').innerText=total.toFixed(0); document.getElementById('cfg-porReceta').innerText=por.toFixed(2); let ff=document.getElementById('f-fijoPorReceta'); if(ff) ff.innerText=por.toFixed(2); let cf=document.getElementById('c-fijos'); if(cf) cf.innerText=por.toFixed(2); calc();}
function calc(){let tot=0; document.querySelectorAll('#insumos > div').forEach(row=>{let subEl=row.querySelector('.in-sub'); if(!subEl) return; if(row.dataset.tipo=='receta'||row.dataset.tipo=='catalogo'){let sel=row.querySelector('.in-salsa'); if(!sel?.options[sel.selectedIndex]) return; let costo=parseFloat(sel.options[sel.selectedIndex].dataset.costo)||0; if(row.dataset.tipo=='catalogo') costo=parseFloat(sel.options[sel.selectedIndex].dataset.venta)||costo; let cant=parseFloat(row.querySelector('.in-salsaCant').value)||0; let sub=costo*cant; subEl.innerText=sub.toFixed(2); tot+=sub;}else{let cc=parseFloat(row.querySelector('.in-cc').value)||0, pc=parseFloat(row.querySelector('.in-pc').value)||0, cu=parseFloat(row.querySelector('.in-cu').value)||0; let uc=row.querySelector('.in-uc').value, uu=row.querySelector('.in-uu').value; if(!cc||!pc||!cu){subEl.innerText='0.00'; return;} let cost=(pc/(cc*baseFactor(uc)))*(cu*baseFactor(uu)); if(uc=='pza'||uu=='pza') cost=(pc/cc)*cu; if(uc=='kg'&&uu=='g') cost=(pc/(cc*1000))*cu; if(uc=='L'&&uu=='ml') cost=(pc/(cc*1000))*cu; subEl.innerText=cost.toFixed(2); tot+=cost;}}); let ci=document.getElementById('c-ing'); if(ci) ci.innerText=tot.toFixed(2); let gf=parseFloat(document.getElementById('c-fijos')?.innerText||'0'); let ce=document.getElementById('costo'); if(ce) ce.innerText=(tot+gf).toFixed(2); let m=parseFloat(document.getElementById('margen').value)||0; let vm=document.getElementById('ventaManual').value; let ve=document.getElementById('venta'); if(ve){ if(vm&&parseFloat(vm)>0) ve.innerText=parseFloat(vm).toFixed(2); else ve.innerText=((tot+gf)*(1+m/100)).toFixed(2);} }
document.getElementById('margen').oninput=calc;
function tab(t){['costos','vender','finanzas','clientes','config'].forEach(x=>{let el=document.getElementById('p-'+x); if(el) el.classList.toggle('hidden',x!=t);}); if(t=='finanzas') mostrarFinanzas();}
function guardar(){let nombre=document.getElementById('nombre').value.trim(); if(!nombre) return alert('Nombre'); let costo=parseFloat(document.getElementById('costo').innerText), venta=parseFloat(document.getElementById('venta').innerText); let ings=[]; document.querySelectorAll('#insumos > div').forEach(row=>{if(row.dataset.tipo=='receta'||row.dataset.tipo=='catalogo'){ings.push({tipo:row.dataset.tipo,id:row.querySelector('.in-salsa').value,cant:row.querySelector('.in-salsaCant').value});} else {ings.push({tipo:'ing',n:row.querySelector('.in-n').value,cc:row.querySelector('.in-cc').value,uc:row.querySelector('.in-uc').value,pc:row.querySelector('.in-pc').value,cu:row.querySelector('.in-cu').value,uu:row.querySelector('.in-uu').value});}}); let p=getProd(); if(editId){let idx=p.findIndex(x=>x.id==editId); if(idx>=0){p[idx].nombre=nombre; p[idx].costo=costo; p[idx].venta=venta; p[idx].tipo=tipoActual; p[idx].ingredientes=ings;}} else {p.push({id:Date.now(),tipo:tipoActual,nombre,costo,venta,ingredientes:ings});} localStorage.setItem('productosV2',JSON.stringify(p)); cancelarEdit(); mostrar();}
function editarProd(id){let p=getProd().find(x=>x.id==id); if(!p) return; editId=id; tipoActual=p.tipo; document.getElementById('nombre').value=p.nombre; document.getElementById('insumos').innerHTML=''; if(p.ingredientes){p.ingredientes.forEach(ing=>{if(ing.tipo=='ing') addInsumo({n:ing.n,cc:ing.cc,uc:ing.uc,pc:ing.pc,cu:ing.cu,uu:ing.uu}); else if(ing.tipo=='receta'){addInsumoSalsa(); let l=document.getElementById('insumos').lastElementChild; l.querySelector('.in-salsa').value=ing.id; l.querySelector('.in-salsaCant').value=ing.cant;} else if(ing.tipo=='catalogo'){addInsumoCatalogo(); let l=document.getElementById('insumos').lastElementChild; l.querySelector('.in-salsa').value=ing.id; l.querySelector('.in-salsaCant').value=ing.cant;}});} tab('costos'); renderCatBotones(); calc(); document.getElementById('btnCancelarEdit').classList.remove('hidden');}
function cancelarEdit(){editId=null; document.getElementById('nombre').value=''; document.getElementById('insumos').innerHTML=''; document.getElementById('ventaManual').value=''; document.getElementById('btnCancelarEdit').classList.add('hidden'); addInsumo({}); calc(); mostrar();}
function mostrar(){let prods=getProd(); let cats=getCats(); let h=''; prods.forEach((p,i)=>{let cat=cats.find(c=>c.id==p.tipo); h+=`<div class="bg-white p-3 rounded-2xl flex gap-3 shadow-sm mt-3 border"><span class="text-[8px] bg-gray-100 px-2 py-1 rounded-full">${cat?cat.nombre:p.tipo}</span><div class="flex-1"><b class="text-[13px]">${p.nombre}</b><br><span class="text-[11px]">$${p.costo.toFixed(2)} → $${p.venta.toFixed(2)}</span></div><button onclick="editarProd(${p.id})" class="bg-blue-50 text-blue-600 px-3 py-1.5 rounded-full text-[11px] font-black">Editar</button><button onclick="if(confirm('¿Borrar?')){let pr=getProd(); pr.splice(${i},1); localStorage.setItem('productosV2',JSON.stringify(pr)); mostrar();}" class="text-red-400 ml-1">X</button></div>`;}); document.getElementById('listaInv').innerHTML=h; mostrarVenta();}
function mostrarVenta(){let cats=getCats(); let catalogoIds=cats.filter(c=>c.grupo=='catalogo').map(c=>c.id); let prods=getProd().filter(p=>catalogoIds.includes(p.tipo)); let h=''; prods.forEach(p=>{h+=`<div class="bg-white rounded-2xl shadow-sm border overflow-hidden"><button onclick="addCart(${p.id})" class="w-full text-left p-2"><b class="text-[12px]">${p.nombre}</b><p class="text-[12px] text-green-600 font-black">$${p.venta.toFixed(2)}</p></button></div>`;}); document.getElementById('listaVenta').innerHTML=h||'<p class="text-sm text-gray-400 text-center py-10">Sin catalogo</p>';}
let carrito=[]; function addCart(id){let p=getProd().find(x=>x.id==id); let ex=carrito.find(x=>x.id==id); if(ex) ex.qty++; else carrito.push({...p,qty:1}); let t=0; carrito.forEach(x=>t+=x.venta*x.qty); document.getElementById('c-total').innerText=t.toFixed(0);}
function cobrar(){if(!carrito.length) return alert('Carrito vacio'); let total=parseFloat(document.getElementById('c-total').innerText); let movs=getMovs(); let now=new Date(); let fechaISO=now.toISOString().split('T')[0]; movs.push({id:Date.now(),tipo:'entrada',concepto:'Venta: '+carrito.map(c=>c.nombre+' x'+c.qty).join(', '),monto:total,fecha:fechaISO,fechaObj:now.getTime(),origen:'venta'}); localStorage.setItem('movs',JSON.stringify(movs)); let facts=getFacturas(); facts.push({id:Date.now()+1,concepto:'Venta catálogo',monto:total,fecha:fechaISO,fechaObj:now.getTime(),tipo:'entrada',catGastoId:'',estado:'pagado',origen:'venta'}); localStorage.setItem('facturas',JSON.stringify(facts)); carrito=[]; document.getElementById('c-total').innerText='0'; tab('finanzas'); vistaFin='flujo'; mostrarFinanzas();}
function addCatGastoFix(){let n=document.getElementById('catGastoNombre').value.trim(); if(!n) return; let cats=getCatGastos(); cats.push({id:Date.now().toString(),nombre:n}); localStorage.setItem('catGastos',JSON.stringify(cats)); document.getElementById('catGastoNombre').value=''; mostrarFinanzas();}
function addProveedorFix(){let n=document.getElementById('provNombre').value.trim(); if(!n) return; let provs=getProveedores(); provs.push({id:Date.now().toString(),nombre:n}); localStorage.setItem('proveedores',JSON.stringify(provs)); document.getElementById('provNombre').value=''; mostrarFinanzas();}
function mostrarFinanzas(){
  let facts=getFacturas(); let provs=getProveedores(); let cats=getCatGastos(); let movs=getMovs();
  document.getElementById('view-flujo').classList.toggle('hidden',vistaFin!='flujo');
  document.getElementById('view-facturas').classList.toggle('hidden',vistaFin!='facturas');
  document.getElementById('view-proveedores').classList.toggle('hidden',vistaFin!='proveedores');
  document.getElementById('view-categorias').classList.toggle('hidden',vistaFin!='categorias');
  document.getElementById('view-fijos').classList.toggle('hidden',vistaFin!='fijos');
  ['flujo','facturas','proveedores','categorias','fijos'].forEach(v=>{let b=document.getElementById('vf-'+v); if(b) b.className=vistaFin==v?'text-[9px] bg-white text-black px-3 py-2 rounded-full font-black whitespace-nowrap':'text-[9px] bg-white/20 text-white px-3 py-2 rounded-full whitespace-nowrap';});
  // mes
  let mesInput=document.getElementById('mesFlujo'); if(!mesInput.value){ mesInput.value=new Date().toISOString().slice(0,7); }
  let [y,m]=mesInput.value.split('-').map(Number); let start=new Date(y,m-1,1).getTime(); let end=new Date(y,m,0,23,59,59).getTime();
  let filtrados=facts.filter(f=>{let t=f.fechaObj||new Date(f.fecha+'T00:00:00').getTime(); return t>=start && t<=end;});
  let entradas=filtrados.filter(f=>f.tipo=='entrada').reduce((s,f)=>s+f.monto,0);
  let salidas=filtrados.filter(f=>f.tipo=='salida').reduce((s,f)=>s+f.monto,0);
  let ganancia=entradas-salidas;
  let porc=entradas>0?((ganancia/entradas)*100).toFixed(1):0;
  document.getElementById('flujo-entradas').innerText=entradas.toFixed(0);
  document.getElementById('flujo-salidas').innerText=salidas.toFixed(0);
  document.getElementById('flujo-ganancia').innerText=ganancia.toFixed(0);
  document.getElementById('flujo-det-entradas').innerText=filtrados.filter(f=>f.tipo=='entrada').length+' movs';
  document.getElementById('flujo-det-salidas').innerText=filtrados.filter(f=>f.tipo=='salida').length+' movs';
  document.getElementById('flujo-porc').innerText=porc+'% margen';
  let total=entradas+salidas||1;
  document.getElementById('flujo-bar-entradas').style.width=(entradas/total*100)+'%';
  document.getElementById('flujo-bar-salidas').style.width=(salidas/total*100)+'%';
  let lista=document.getElementById('flujo-lista'); let h='';
  if(!filtrados.length){ h='<p class="text-center text-[12px] text-gray-400 py-8">Sin movimientos este mes.<br>Dale + para agregar gasto o cobra en Catalogo</p>'; }
  else {
    filtrados.sort((a,b)=>b.fechaObj-a.fechaObj).forEach(f=>{
      let cat=cats.find(c=>c.id==f.catGastoId); let esEntrada=f.tipo=='entrada';
      h+=`<div class="flex justify-between items-center py-2.5 border-b border-gray-100"><div class="flex items-center gap-2"><div class="w-8 h-8 rounded-full flex items-center justify-center text-[12px] ${esEntrada?'bg-green-100':'bg-red-100'}">${esEntrada?'💰':'💸'}</div><div><p class="text-[12px] font-bold">${f.concepto}</p><p class="text-[10px] text-gray-400">${f.fecha} ${cat?'• '+cat.nombre:''} ${f.origen=='venta'?'• Venta':''}</p></div></div><div class="text-right"><p class="font-black text-[13px] ${esEntrada?'text-green-600':'text-red-600'}">${esEntrada?'+':'-'}$${f.monto.toFixed(0)}</p><button onclick="if(confirm('¿Borrar?')){let fs=getFacturas(); fs=fs.filter(x=>x.id!=${f.id}); localStorage.setItem('facturas',JSON.stringify(fs)); let ms=getMovs(); ms=ms.filter(x=>x.id!=${f.id}); localStorage.setItem('movs',JSON.stringify(ms)); mostrarFinanzas();}" class="text-[9px] text-gray-300">Borrar</button></div></div>`;
    });
  }
  if(lista) lista.innerHTML=h;
  if(vistaFin=='categorias'){let hh=''; cats.forEach((c,i)=>{hh+=`<div class="flex justify-between items-center bg-gray-50 p-3 rounded-xl mt-2 border"><b class="text-[13px]">${c.nombre}</b><button onclick="let cs=getCatGastos(); cs.splice(${i},1); localStorage.setItem('catGastos',JSON.stringify(cs)); mostrarFinanzas();" class="text-red-400">X</button></div>`;}); document.getElementById('listaCatGastos').innerHTML=hh;}
  if(vistaFin=='proveedores'){let hh=''; provs.forEach((p,i)=>{hh+=`<div class="flex justify-between bg-gray-50 p-3 rounded-xl mt-2"><b>${p.nombre}</b><button onclick="let pr=getProveedores(); pr.splice(${i},1); localStorage.setItem('proveedores',JSON.stringify(pr)); mostrarFinanzas();" class="text-red-400">X</button></div>`;}); document.getElementById('listaProveedores').innerHTML=hh;}
  if(vistaFin=='facturas'){let hh=''; filtrados.slice().reverse().forEach(f=>{hh+=`<div class="flex justify-between py-2 border-b"><div><p class="text-[12px] font-bold">${f.concepto}</p><p class="text-[10px] text-gray-400">${f.fecha} - ${f.tipo}</p></div><b class="${f.tipo=='entrada'?'text-green-600':'text-red-600'}">$${f.monto}</b></div>`;}); document.getElementById('f-lista').innerHTML=hh||'<p class="text-center py-6 text-gray-400">Sin movimientos</p>';}
}
function openModalGasto(){let provs=getProveedores(); let cats=getCatGastos(); document.getElementById('g-proveedor').innerHTML='<option value="">Sin proveedor</option>'+provs.map(p=>`<option value="${p.id}">${p.nombre}</option>`).join(''); document.getElementById('g-catGasto').innerHTML='<option value="">Sin categoria</option>'+cats.map(c=>`<option value="${c.id}">${c.nombre}</option>`).join(''); document.getElementById('modalGasto').classList.remove('hidden');}
function addFactura(){let concepto=document.getElementById('g-concepto').value.trim(), monto=parseFloat(document.getElementById('g-monto').value), fecha=document.getElementById('g-fecha').value; if(!concepto||!monto||!fecha) return alert('Faltan datos'); let facts=getFacturas(); facts.push({id:Date.now(),concepto,monto,fecha,fechaObj:new Date(fecha+'T00:00:00').getTime(),tipo:document.getElementById('g-tipo').value,proveedorId:document.getElementById('g-proveedor').value,catGastoId:document.getElementById('g-catGasto').value,estado:'pendiente'}); localStorage.setItem('facturas',JSON.stringify(facts)); if(document.getElementById('g-tipo').value=='entrada'){ let movs=getMovs(); movs.push({id:Date.now(),tipo:'entrada',concepto,monto,fecha,fechaObj:new Date(fecha+'T00:00:00').getTime()}); localStorage.setItem('movs',JSON.stringify(movs)); } document.getElementById('modalGasto').classList.add('hidden'); document.getElementById('g-concepto').value=''; document.getElementById('g-monto').value=''; mostrarFinanzas();}
function getCatsFull(){return getCats();}
function renderCats(){let cats=getCatsFull(); let h=''; cats.forEach((cat,i)=>{h+=`<div class="flex gap-2 items-center bg-gray-50 p-2 rounded-xl mt-2"><input value="${cat.nombre}" onchange="let cs=getCats(); cs[${i}].nombre=this.value; localStorage.setItem('categoriasV2',JSON.stringify(cs)); renderCats(); renderCatBotones();" class="flex-1 bg-transparent font-bold text-sm"><span class="text-[9px] ${cat.grupo=='recetario'?'bg-amber-200':'bg-black text-white'} px-2 py-0.5 rounded-full">${cat.grupo}</span><button onclick="let cs=getCats(); cs.splice(${i},1); localStorage.setItem('categoriasV2',JSON.stringify(cs)); renderCats(); renderCatBotones();" class="text-red-400">x</button></div>`;}); document.getElementById('listaCats').innerHTML=h;}
function renderCatBotones(){let cats=getCats(); let sel=cats.find(c=>c.id==tipoActual)||cats[0]; if(sel) tipoActual=sel.id; let isRec=sel?.grupo=='recetario'; let bR=document.getElementById('bRec'), bC=document.getElementById('bCat'); if(bR) bR.className=isRec?'flex-1 py-3 rounded-2xl text-[11px] font-black bg-black text-white':'flex-1 py-3 rounded-2xl text-[11px] font-black bg-gray-100'; if(bC) bC.className=!isRec?'flex-1 py-3 rounded-2xl text-[11px] font-black bg-black text-white':'flex-1 py-3 rounded-2xl text-[11px] font-black bg-gray-100'; let btnC=document.getElementById('btnComplemento'); if(btnC) btnC.classList.toggle('hidden',isRec);}
function setTipoCat(g){let cats=getCats().filter(c=>c.grupo==g); if(cats.length) tipoActual=cats[0].id; renderCatBotones();}
function addCategoria(){let n=document.getElementById('newCat').value.trim(), g=document.getElementById('newCatTipo').value; if(!n) return; let cats=getCats(); cats.push({id:Date.now().toString(),nombre:n,grupo:g}); document.getElementById('newCat').value=''; localStorage.setItem('categoriasV2',JSON.stringify(cats)); renderCats(); renderCatBotones();}
function tab(t){['costos','vender','finanzas','clientes','config'].forEach(x=>{let el=document.getElementById('p-'+x); if(el) el.classList.toggle('hidden',x!=t);}); if(t=='finanzas') mostrarFinanzas();}
let gf=JSON.parse(localStorage.getItem('gastosFijos')||'[]'); if(gf.length){gf.forEach(g=>addGastoFijo(g));} else {addGastoFijo({nombre:'Renta',monto:3000}); addGastoFijo({nombre:'Luz',monto:800});}
document.getElementById('prodMes').value=localStorage.getItem('prodMes')||100;
let today=new Date().toISOString().split('T')[0]; let gfe=document.getElementById('g-fecha'); if(gfe) gfe.value=today; let mesEl=document.getElementById('mesFlujo'); if(mesEl) mesEl.value=new Date().toISOString().slice(0,7);
renderCats(); renderCatBotones(); calcGastosFijos(); addInsumo({n:'Leche',cc:1,uc:'L',pc:40,cu:250,uu:'ml'}); calc(); mostrar(); mostrarFinanzas();
</script></body></html>
"""
